/**
 * PrintLayout.jsx
 * Professional wrapper for luxury document printing
 *
 * Provides:
 * - Consistent header with document info
 * - Footer with metadata
 * - Professional page structure
 * - Document versioning
 */

import React from 'react';
import { useSelector } from 'react-redux';
import { selectPolicyMeta, selectHenry } from '../store/selectors';

const PrintLayout = ({ children, documentType: _documentType, documentTitle }) => {
  const policyMeta = useSelector(selectPolicyMeta);
  const henry = useSelector(selectHenry);

  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <div className="print-layout" role="document">
      {/* Document Header - Print on first page only */}
      <div className="print-layout__header" role="banner" aria-label="Document header">
        <div className="print-layout__brand">
          <h4 style={{ margin: '0 0 4pt 0', color: '#6b7280', fontSize: '9pt' }}>
            White Caves Real Estate L.L.C
          </h4>
          <p style={{ margin: '0', fontSize: '8pt', color: '#9ca3af' }}>DED License: 1388443 | Dubai, UAE</p>
        </div>
      </div>

      {/* Document Content */}
      <div className="print-layout__content" role="main">
        {children}
      </div>

      {/* Document Footer - Print on final page */}
      <div className="print-layout__footer" role="contentinfo" aria-label="Document footer">
        <p style={{ margin: '0', fontSize: '9pt', color: '#9ca3af', textAlign: 'center' }}>
          {documentTitle} • Policy v{policyMeta.version} • Generated {today}
        </p>
        <p style={{ margin: '4pt 0 0 0', fontSize: '8pt', color: '#bdbdbd', textAlign: 'center' }}>
          Generated by {henry.name} — {henry.title} ({henry.aiId})
        </p>
      </div>

      {/* Print Styles for Layout Management */}
      <style>{`
        @media print {
          .print-layout {
            display: block;
            width: 100%;
          }

          .print-layout__header {
            margin-bottom: 8pt;
            padding-bottom: 6pt;
            border-bottom: 1pt solid #e5e7eb;
            page-break-after: avoid;
          }

          .print-layout__brand {
            page-break-inside: avoid;
          }

          .print-layout__content {
            margin: 8pt 0;
          }

          .print-layout__footer {
            margin-top: 12pt;
            padding-top: 8pt;
            border-top: 1pt solid #e5e7eb;
            page-break-before: avoid;
            page-break-inside: avoid;
          }
        }

        /* Screen display only */
        @media screen {
          .print-layout {
            background: #fff;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            padding: 24px;
            max-width: 900px;
            margin: 0 auto;
          }

          .print-layout__header {
            margin-bottom: 16px;
            padding-bottom: 12px;
            border-bottom: 2px solid #e5e7eb;
          }

          .print-layout__content {
            margin: 16px 0;
            min-height: 300px;
          }

          .print-layout__footer {
            margin-top: 20px;
            padding-top: 12px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
          }
        }
      `}</style>
    </div>
  );
};

export default React.memo(PrintLayout);
