/**
 * useDocuments — Data hook for document generation and management
 *
 * Provides:
 *   - Actions: generate, fetch, list documents
 *   - Data: documents list, document types, current document
 *   - State: loading, error
 */

import { useCallback, useState } from 'react';
import { useDispatch } from 'react-redux';
import type { AppDispatch } from '../../store';
import {
  generateDocumentAPI,
  fetchDocumentsAPI,
  fetchDocumentTypesAPI,
  autoGenerateDocumentAPI,
  previewAutoFillAPI,
  fetchAutoFillEntitiesAPI,
} from '../../store/crmDataSlice';

interface DocumentItem {
  id: string;
  type: string;
  title: string;
  version: number;
  status: string;
  htmlContent: string;
  metadata: Record<string, unknown> | null;
  createdAt: string;
}

interface DocumentType {
  type: string;
  label: string;
}

interface AutoFillEntity {
  type: string;
  label: string;
  requiredEntities: string[];
  optionalEntities: string[];
}

interface AutoFillContext {
  type: string;
  entitiesUsed: string[];
  clauseSelections: Record<string, string>;
  missingFields: string[];
}

interface AutoFillInput {
  type: string;
  leadId?: string;
  propertyId?: string;
  transactionId?: string;
  commissionId?: string;
  viewingId?: string;
  leaseId?: string;
  offerId?: string;
  overrides?: Record<string, string>;
}

export function useDocuments() {
  const dispatch = useDispatch<AppDispatch>();
  const [documents, setDocuments] = useState<DocumentItem[]>([]);
  const [documentTypes, setDocumentTypes] = useState<DocumentType[]>([]);
  const [currentDocument, setCurrentDocument] = useState<DocumentItem | null>(null);
  const [autoFillEntities, setAutoFillEntities] = useState<AutoFillEntity[]>([]);
  const [autoFillPreview, setAutoFillPreview] = useState<{ variables: Record<string, string>; context: AutoFillContext } | null>(null);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  /** Generate a new document from template */
  const generateDocument = useCallback(
    async (input: {
      type: string;
      variables: Record<string, string>;
      transactionId?: string;
      leadId?: string;
      propertyId?: string;
      commissionId?: string;
    }) => {
      setLoading(true);
      setError(null);
      try {
        const result = await dispatch(generateDocumentAPI(input)).unwrap();
        setCurrentDocument(result as unknown as DocumentItem);
        return result;
      } catch (err) {
        setError(typeof err === 'string' ? err : 'Failed to generate document');
        return null;
      } finally {
        setLoading(false);
      }
    },
    [dispatch],
  );

  /** Fetch documents list with optional filters */
  const fetchDocuments = useCallback(
    async (filters?: { type?: string; status?: string; leadId?: string; propertyId?: string; page?: number; pageSize?: number }) => {
      setLoading(true);
      setError(null);
      try {
        const result = await dispatch(fetchDocumentsAPI(filters)).unwrap();
        setDocuments(result.data as unknown as DocumentItem[]);
        setTotal(result.total);
      } catch (err) {
        setError(typeof err === 'string' ? err : 'Failed to fetch documents');
      } finally {
        setLoading(false);
      }
    },
    [dispatch],
  );

  /** Fetch available document types */
  const fetchTypes = useCallback(async () => {
    setError(null);
    try {
      const types = await dispatch(fetchDocumentTypesAPI()).unwrap();
      setDocumentTypes(types);
    } catch (err) {
      setError(typeof err === 'string' ? err : 'Failed to fetch document types');
    }
  }, [dispatch]);

  /** Auto-generate a document from DB records (Phase 4B) */
  const autoGenerateDocument = useCallback(
    async (input: AutoFillInput) => {
      setLoading(true);
      setError(null);
      try {
        const result = await dispatch(autoGenerateDocumentAPI(input)).unwrap();
        setCurrentDocument(result.document as unknown as DocumentItem);
        return result;
      } catch (err) {
        setError(typeof err === 'string' ? err : 'Failed to auto-generate document');
        return null;
      } finally {
        setLoading(false);
      }
    },
    [dispatch],
  );

  /** Preview auto-filled variables before generating */
  const previewAutoFill = useCallback(
    async (input: AutoFillInput) => {
      setLoading(true);
      setError(null);
      try {
        const result = await dispatch(previewAutoFillAPI(input)).unwrap();
        setAutoFillPreview(result as unknown as { variables: Record<string, string>; context: AutoFillContext });
        return result;
      } catch (err) {
        setError(typeof err === 'string' ? err : 'Failed to preview auto-fill');
        return null;
      } finally {
        setLoading(false);
      }
    },
    [dispatch],
  );

  /** Fetch auto-fill entity requirements per document type */
  const fetchAutoFillEntities = useCallback(async () => {
    setError(null);
    try {
      const entities = await dispatch(fetchAutoFillEntitiesAPI()).unwrap();
      setAutoFillEntities(entities);
    } catch (err) {
      setError(typeof err === 'string' ? err : 'Failed to fetch auto-fill entities');
    }
  }, [dispatch]);

  return {
    // Data
    documents,
    documentTypes,
    currentDocument,
    autoFillEntities,
    autoFillPreview,
    total,

    // State
    loading,
    error,

    // Actions
    generateDocument,
    fetchDocuments,
    fetchTypes,

    // Auto-fill actions (Phase 4B)
    autoGenerateDocument,
    previewAutoFill,
    fetchAutoFillEntities,
  };
}
