export const FEATURE_CATEGORIES = {
  AUTHENTICATION: 'authentication',
  USER_MANAGEMENT: 'user_management',
  PROPERTY: 'property',
  TRANSACTIONS: 'transactions',
  COMMUNICATION: 'communication',
  ANALYTICS: 'analytics',
  INTEGRATIONS: 'integrations',
  UI_COMPONENTS: 'ui_components',
  TOOLS: 'tools',
  SYSTEM: 'system',
};

export const FEATURE_STATUS = {
  ACTIVE: 'active',
  BETA: 'beta',
  DEVELOPMENT: 'development',
  PLANNED: 'planned',
  DEPRECATED: 'deprecated',
};

export const PLATFORM_FEATURES = [
  {
    id: 'multi_provider_auth',
    name: 'Multi-Provider Authentication',
    category: FEATURE_CATEGORIES.AUTHENTICATION,
    status: FEATURE_STATUS.ACTIVE,
    icon: '🔐',
    description: 'Sign in with multiple authentication providers for secure access',
    details: [
      'Google Sign-In',
      'Facebook Login',
      'Apple Sign-In',
      'LinkedIn Authentication',
      'Email/Password',
      'Mobile OTP (SMS)',
      'UAE Pass Integration (Ready)',
    ],
    implementedDate: '2024-01-15',
    files: ['src/pages/auth/SignInPage.jsx', 'src/features/auth/'],
  },
  {
    id: 'biometric_auth',
    name: 'Biometric Authentication',
    category: FEATURE_CATEGORIES.AUTHENTICATION,
    status: FEATURE_STATUS.ACTIVE,
    icon: '👆',
    description: 'Face ID and Touch ID login using WebAuthn/Passkeys',
    details: [
      'WebAuthn credential registration',
      'Face ID / Touch ID support',
      'Secure passkey storage',
      'Cross-device authentication',
      'Biometric session management',
    ],
    implementedDate: '2024-03-10',
    files: ['src/features/auth/components/BiometricLogin/', 'src/services/webAuthnService.js'],
  },
  {
    id: 'role_based_access',
    name: 'Role-Based Access Control',
    category: FEATURE_CATEGORIES.USER_MANAGEMENT,
    status: FEATURE_STATUS.ACTIVE,
    icon: '👥',
    description: 'Comprehensive multi-role system with 7 user types',
    details: [
      'Buyer role with property search',
      'Seller role with listing management',
      'Landlord role with tenant management',
      'Tenant role with lease tracking',
      'Leasing Agent dashboard',
      'Sales Agent pipeline',
      'Company Owner full access',
    ],
    implementedDate: '2024-01-20',
    files: ['src/utils/permissions.js', 'src/hooks/usePermissions.js'],
  },
  {
    id: 'role_approval_workflow',
    name: 'Role Approval Workflow',
    category: FEATURE_CATEGORIES.USER_MANAGEMENT,
    status: FEATURE_STATUS.ACTIVE,
    icon: '✅',
    description: 'Admin approval system for user role requests',
    details: [
      'Pending role request queue',
      'Admin approval/rejection',
      'Email notifications',
      'Audit trail logging',
    ],
    implementedDate: '2024-02-05',
    files: ['src/features/admin/components/approvals/'],
  },
  {
    id: 'property_listings',
    name: 'Property Listings Management',
    category: FEATURE_CATEGORIES.PROPERTY,
    status: FEATURE_STATUS.ACTIVE,
    icon: '🏠',
    description: 'Full property listing CRUD with advanced features',
    details: [
      'Property creation and editing',
      'Image gallery with full-screen view',
      'Property details and specifications',
      'Location mapping with Google Maps',
      'Property comparison tool',
      'Favorites and saved properties',
    ],
    implementedDate: '2024-01-25',
    files: ['src/pages/PropertiesPage.jsx', 'src/shared/components/properties/'],
  },
  {
    id: 'advanced_search',
    name: 'Advanced Property Search',
    category: FEATURE_CATEGORIES.PROPERTY,
    status: FEATURE_STATUS.ACTIVE,
    icon: '🔍',
    description: 'Powerful search with filters and interactive map',
    details: [
      'Multi-filter search (price, type, area)',
      'Interactive Dubai SVG map',
      'Neighborhood filtering',
      'Sort by price, date, popularity',
      'Save search preferences',
    ],
    implementedDate: '2024-02-10',
    files: ['src/components/properties/PropertySearch.jsx'],
  },
  {
    id: 'ejari_contracts',
    name: 'Ejari Tenancy Contracts',
    category: FEATURE_CATEGORIES.TRANSACTIONS,
    status: FEATURE_STATUS.ACTIVE,
    icon: '📜',
    description: 'UAE-compliant tenancy contract generation and signing',
    details: [
      'Ejari-compliant contract templates',
      'Digital signature capture',
      'PDF contract generation',
      'Contract status tracking',
      'Google Drive storage integration',
    ],
    implementedDate: '2024-02-20',
    files: ['src/pages/SignContractPage.jsx', 'server/routes/contracts.routes.js'],
  },
  {
    id: 'transaction_timelines',
    name: 'Transaction Timelines',
    category: FEATURE_CATEGORIES.TRANSACTIONS,
    status: FEATURE_STATUS.ACTIVE,
    icon: '📅',
    description: 'Comprehensive deal tracking with stage progression',
    details: [
      'Tenancy timeline (16 stages)',
      'Sale timeline (14 stages)',
      'Document tracking per stage',
      'Verification workflows',
      'Status notifications',
    ],
    implementedDate: '2024-03-01',
    files: ['server/models/Timeline.js', 'server/routes/timelines.routes.js'],
  },
  {
    id: 'stripe_payments',
    name: 'Stripe Payment Processing',
    category: FEATURE_CATEGORIES.TRANSACTIONS,
    status: FEATURE_STATUS.ACTIVE,
    icon: '💳',
    description: 'Secure payment processing for property transactions',
    details: [
      'Stripe checkout integration',
      'Secure payment forms',
      'Payment intent handling',
      'Receipt generation',
      'Transaction history',
    ],
    implementedDate: '2024-02-15',
    files: ['server/routes/payments.routes.js'],
  },
  {
    id: 'whatsapp_business',
    name: 'WhatsApp Business Integration',
    category: FEATURE_CATEGORIES.COMMUNICATION,
    status: FEATURE_STATUS.ACTIVE,
    icon: '💬',
    description: 'Full WhatsApp Business messaging platform',
    details: [
      'Real-time chat interface',
      'AI-powered chatbot',
      'Message templates',
      'Contact management',
      'Analytics dashboard',
      'Lead scoring',
    ],
    implementedDate: '2024-03-15',
    files: ['src/pages/owner/WhatsAppDashboardPage.jsx', 'server/routes/whatsapp.routes.js'],
  },
  {
    id: 'ai_chatbot',
    name: 'AI Chatbot Service',
    category: FEATURE_CATEGORIES.COMMUNICATION,
    status: FEATURE_STATUS.ACTIVE,
    icon: '🤖',
    description: 'Intelligent chatbot with bilingual support',
    details: [
      'Intent classification',
      'Entity extraction',
      'Arabic/English bilingual',
      'Context management',
      'Property recommendations',
      'Lead qualification',
    ],
    implementedDate: '2024-03-20',
    files: ['src/services/chatbotService.js', 'src/data/chatbotTrainingData.js'],
  },
  {
    id: 'speed_insights',
    name: 'Web Performance Insights',
    category: FEATURE_CATEGORIES.ANALYTICS,
    status: FEATURE_STATUS.ACTIVE,
    icon: '⚡',
    description: 'Real-time Core Web Vitals and traffic monitoring',
    details: [
      'LCP, INP, CLS, FCP, TTFB tracking',
      'Performance score calculation',
      'Traffic metrics dashboard',
      'Auto-refresh monitoring',
      'Vercel Speed Insights integration',
    ],
    implementedDate: '2024-03-25',
    files: ['src/store/analyticsSlice.js', 'src/components/analytics/WebVitalsTracker.jsx'],
  },
  {
    id: 'market_analytics',
    name: 'Market Analytics Dashboard',
    category: FEATURE_CATEGORIES.ANALYTICS,
    status: FEATURE_STATUS.ACTIVE,
    icon: '📊',
    description: 'Real estate market insights and KPIs',
    details: [
      'Transaction breakdowns',
      'Lead source visualization',
      'Agent performance leaderboards',
      'Revenue tracking',
      'Conversion rates',
    ],
    implementedDate: '2024-02-28',
    files: ['src/pages/owner/OwnerDashboardPage.jsx'],
  },
  {
    id: 'google_calendar',
    name: 'Google Calendar Integration',
    category: FEATURE_CATEGORIES.INTEGRATIONS,
    status: FEATURE_STATUS.ACTIVE,
    icon: '📆',
    description: 'Appointment scheduling and reminders',
    details: [
      'Property viewing events',
      'Follow-up task creation',
      'Meeting invitations',
      'Calendar sync',
    ],
    implementedDate: '2024-02-25',
    files: ['server/services/googleCalendarService.js'],
  },
  {
    id: 'google_drive',
    name: 'Google Drive Storage',
    category: FEATURE_CATEGORIES.INTEGRATIONS,
    status: FEATURE_STATUS.ACTIVE,
    icon: '📁',
    description: 'Cloud storage for contracts and documents',
    details: [
      'Signed contract storage',
      'Document organization',
      'Secure sharing',
      'Automatic backups',
    ],
    implementedDate: '2024-02-20',
    files: ['server/services/googleDriveService.js'],
  },
  {
    id: 'google_maps',
    name: 'Google Maps Integration',
    category: FEATURE_CATEGORIES.INTEGRATIONS,
    status: FEATURE_STATUS.ACTIVE,
    icon: '🗺️',
    description: 'Property location visualization and search',
    details: [
      'Interactive property maps',
      'Location markers',
      'Neighborhood boundaries',
      'Distance calculations',
    ],
    implementedDate: '2024-01-30',
    files: ['src/components/maps/'],
  },
  {
    id: 'firebase_auth',
    name: 'Firebase Authentication',
    category: FEATURE_CATEGORIES.INTEGRATIONS,
    status: FEATURE_STATUS.ACTIVE,
    icon: '🔥',
    description: 'Secure authentication infrastructure',
    details: [
      'Social login providers',
      'Email verification',
      'Password reset',
      'Session management',
      'Admin SDK integration',
    ],
    implementedDate: '2024-01-15',
    files: ['src/config/firebase.js', 'server/config/firebase-admin.js'],
  },
  {
    id: 'mongodb_database',
    name: 'MongoDB Database',
    category: FEATURE_CATEGORIES.INTEGRATIONS,
    status: FEATURE_STATUS.ACTIVE,
    icon: '🍃',
    description: 'Document-based data storage',
    details: [
      'Mongoose ODM',
      'User schema with roles',
      'Property documents',
      'Contract storage',
      'Message history',
    ],
    implementedDate: '2024-01-15',
    files: ['server/models/', 'server/config/database.js'],
  },
  {
    id: 'universal_nav',
    name: 'Universal Navigation',
    category: FEATURE_CATEGORIES.UI_COMPONENTS,
    status: FEATURE_STATUS.ACTIVE,
    icon: '🧭',
    description: 'Consistent navigation across all pages',
    details: [
      'Role-based menu items',
      'Profile dropdown',
      'Theme toggle',
      'Mobile responsive',
    ],
    implementedDate: '2024-01-25',
    files: ['src/components/common/UniversalNav.jsx'],
  },
  {
    id: 'content_slider',
    name: 'Content Slider Component',
    category: FEATURE_CATEGORIES.UI_COMPONENTS,
    status: FEATURE_STATUS.ACTIVE,
    icon: '🎠',
    description: 'Responsive carousel for dynamic content',
    details: [
      'Touch/drag support',
      'Auto-play option',
      'Responsive slides-per-view',
      'Custom render support',
    ],
    implementedDate: '2024-02-01',
    files: ['src/components/common/ContentSlider.jsx'],
  },
  {
    id: 'status_notifications',
    name: 'Status Notification System',
    category: FEATURE_CATEGORIES.UI_COMPONENTS,
    status: FEATURE_STATUS.ACTIVE,
    icon: '🔔',
    description: 'Global toast notifications for events',
    details: [
      'Success (green) notifications',
      'Error (red) alerts',
      'Warning (amber) messages',
      'Info (blue) notices',
      'Auto-dismiss with progress',
    ],
    implementedDate: '2024-03-25',
    files: ['src/components/common/StatusNotification.jsx'],
  },
  {
    id: 'dark_mode',
    name: 'Dark/Light Theme',
    category: FEATURE_CATEGORIES.UI_COMPONENTS,
    status: FEATURE_STATUS.ACTIVE,
    icon: '🌙',
    description: 'Full dark mode support across application',
    details: [
      'System preference detection',
      'User preference storage',
      'CSS variable theming',
      'Smooth transitions',
    ],
    implementedDate: '2024-01-20',
    files: ['src/styles/theme.css'],
  },
  {
    id: 'rtl_support',
    name: 'RTL Language Support',
    category: FEATURE_CATEGORIES.UI_COMPONENTS,
    status: FEATURE_STATUS.ACTIVE,
    icon: '🔄',
    description: 'Arabic right-to-left layout support',
    details: [
      'RTL CSS styles',
      'Arabic translations',
      'Bilingual content',
      'Direction switching',
    ],
    implementedDate: '2024-02-15',
    files: ['src/styles/rtl.css', 'src/context/LanguageContext.jsx'],
  },
  {
    id: 'mortgage_calculator',
    name: 'Mortgage Calculator',
    category: FEATURE_CATEGORIES.TOOLS,
    status: FEATURE_STATUS.ACTIVE,
    icon: '🧮',
    description: 'UAE-specific mortgage calculation tool',
    details: [
      'Monthly payment calculation',
      'Interest rate comparison',
      'Amortization schedule',
      'Bank rate options',
    ],
    implementedDate: '2024-02-10',
    files: ['src/pages/buyer/MortgageCalculatorPage.jsx'],
  },
  {
    id: 'dld_fees_calculator',
    name: 'DLD Fees Calculator',
    category: FEATURE_CATEGORIES.TOOLS,
    status: FEATURE_STATUS.ACTIVE,
    icon: '📋',
    description: 'Dubai Land Department fee estimation',
    details: [
      'Transfer fee calculation',
      'Registration fees',
      'Agent commission',
      'Total cost breakdown',
    ],
    implementedDate: '2024-02-10',
    files: ['src/pages/buyer/DLDFeesPage.jsx'],
  },
  {
    id: 'rent_vs_buy',
    name: 'Rent vs Buy Calculator',
    category: FEATURE_CATEGORIES.TOOLS,
    status: FEATURE_STATUS.ACTIVE,
    icon: '⚖️',
    description: 'Smart comparison tool for rent or purchase decision',
    details: [
      'Break-even analysis',
      'Investment comparison',
      'Market trend factors',
      'Personalized recommendations',
    ],
    implementedDate: '2024-03-05',
    files: ['src/components/tools/RentVsBuyCalculator.jsx'],
  },
  {
    id: 'virtual_tours',
    name: 'Virtual Tour Gallery',
    category: FEATURE_CATEGORIES.TOOLS,
    status: FEATURE_STATUS.ACTIVE,
    icon: '🎬',
    description: 'Matterport 3D tour integration',
    details: [
      'Embedded 3D tours',
      'Full-screen viewing',
      'Multiple tour support',
      'Mobile optimized',
    ],
    implementedDate: '2024-03-01',
    files: ['src/components/properties/VirtualTourGallery.jsx'],
  },
  {
    id: 'system_health',
    name: 'System Health Monitor',
    category: FEATURE_CATEGORIES.SYSTEM,
    status: FEATURE_STATUS.ACTIVE,
    icon: '🩺',
    description: 'Real-time service status monitoring',
    details: [
      'Server status',
      'Database connectivity',
      'API health checks',
      'Environment variables',
      'Deployment readiness',
    ],
    implementedDate: '2024-03-15',
    files: ['src/pages/owner/SystemHealthPage.jsx', 'server/routes/system.routes.js'],
  },
  {
    id: 'agent_assignment',
    name: 'AI Agent Assignment Engine',
    category: FEATURE_CATEGORIES.SYSTEM,
    status: FEATURE_STATUS.ACTIVE,
    icon: '🎯',
    description: 'Intelligent agent matching algorithm',
    details: [
      'Expertise scoring (35%)',
      'Availability check (25%)',
      'Performance rating (20%)',
      'Proximity factor (10%)',
      'Client match (10%)',
    ],
    implementedDate: '2024-03-10',
    files: ['src/services/agentAssignmentService.js'],
  },
  {
    id: 'redux_state',
    name: 'Redux State Management',
    category: FEATURE_CATEGORIES.SYSTEM,
    status: FEATURE_STATUS.ACTIVE,
    icon: '🔄',
    description: 'Centralized application state',
    details: [
      'User slice',
      'Property slice',
      'Navigation slice',
      'Dashboard slice',
      'Content slice',
      'Auth slice',
      'Analytics slice',
    ],
    implementedDate: '2024-01-15',
    files: ['src/store/'],
  },
  {
    id: 'session_management',
    name: 'Session Management',
    category: FEATURE_CATEGORIES.AUTHENTICATION,
    status: FEATURE_STATUS.ACTIVE,
    icon: '⏱️',
    description: 'Enhanced session tracking and security',
    details: [
      'Multi-session tracking',
      'Device detection',
      'Session timeout',
      'Token refresh',
      'Activity monitoring',
    ],
    implementedDate: '2024-02-20',
    files: ['src/store/authSlice.js'],
  },
  {
    id: 'seo_optimization',
    name: 'SEO Optimization',
    category: FEATURE_CATEGORIES.SYSTEM,
    status: FEATURE_STATUS.ACTIVE,
    icon: '🔎',
    description: 'Search engine optimization features',
    details: [
      'Meta tags management',
      'Open Graph support',
      'Twitter Cards',
      'JSON-LD structured data',
      'Sitemap generation',
      'robots.txt',
    ],
    implementedDate: '2024-02-15',
    files: ['index.html', 'public/'],
  },
];

export const getFeaturesByCategory = (category) => {
  return PLATFORM_FEATURES.filter(f => f.category === category);
};

export const getFeatureById = (id) => {
  return PLATFORM_FEATURES.find(f => f.id === id);
};

export const getActiveFeatures = () => {
  return PLATFORM_FEATURES.filter(f => f.status === FEATURE_STATUS.ACTIVE);
};

export const getFeatureStats = () => {
  const stats = {
    total: PLATFORM_FEATURES.length,
    byCategory: {},
    byStatus: {},
  };
  
  PLATFORM_FEATURES.forEach(f => {
    stats.byCategory[f.category] = (stats.byCategory[f.category] || 0) + 1;
    stats.byStatus[f.status] = (stats.byStatus[f.status] || 0) + 1;
  });
  
  return stats;
};

export const CATEGORY_INFO = {
  [FEATURE_CATEGORIES.AUTHENTICATION]: { name: 'Authentication', icon: '🔐', color: '#DC2626' },
  [FEATURE_CATEGORIES.USER_MANAGEMENT]: { name: 'User Management', icon: '👥', color: '#2563EB' },
  [FEATURE_CATEGORIES.PROPERTY]: { name: 'Property', icon: '🏠', color: '#16A34A' },
  [FEATURE_CATEGORIES.TRANSACTIONS]: { name: 'Transactions', icon: '💰', color: '#D4AF37' },
  [FEATURE_CATEGORIES.COMMUNICATION]: { name: 'Communication', icon: '💬', color: '#8B5CF6' },
  [FEATURE_CATEGORIES.ANALYTICS]: { name: 'Analytics', icon: '📊', color: '#EC4899' },
  [FEATURE_CATEGORIES.INTEGRATIONS]: { name: 'Integrations', icon: '🔗', color: '#14B8A6' },
  [FEATURE_CATEGORIES.UI_COMPONENTS]: { name: 'UI Components', icon: '🎨', color: '#F59E0B' },
  [FEATURE_CATEGORIES.TOOLS]: { name: 'Tools & Calculators', icon: '🧮', color: '#6366F1' },
  [FEATURE_CATEGORIES.SYSTEM]: { name: 'System', icon: '⚙️', color: '#64748B' },
};
