// ============================================================================
// AI ASSISTANT DASHBOARD — REGISTRY DATA & SEED GENERATORS
// Extracted from aiAssistantDashboardSlice.tsx for maintainability
// ============================================================================

import type {
  AIAssistant,
  Activity,
  Notification,
  Task,
} from './types';

// ============================================================================
// AI ASSISTANTS REGISTRY
// ============================================================================

export const AI_ASSISTANTS_REGISTRY: Record<string, AIAssistant> = {
  mary: {
    id: 'mary',
    name: 'Mary',
    title: 'Inventory & Data Manager',
    department: 'operations',
    icon: 'FileText',
    colorScheme: '#3B82F6',
    avatar: '👩‍💻',
    description:
      'Manages DAMAC Hills 2 property inventory with 9,378+ units, data acquisition tools, and asset management',
    capabilities: [
      'property_crud',
      'data_tools',
      'asset_fetcher',
      'filtering',
      'excel_import',
      'ocr_extraction',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'sales_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 156,
      activeUsers: 3,
      systemHealth: 'optimal',
    },
    quickStats: { value: 9378, label: 'Properties', change: 0 },
    dashboardUrl: '/owner/dashboard?tab=mary',
    apiEndpoints: ['/api/inventory', '/api/properties', '/api/assets'],
  },
  theodora: {
    id: 'theodora',
    name: 'Theodora',
    title: 'Finance & Accounts Director',
    department: 'finance',
    icon: 'DollarSign',
    colorScheme: '#F59E0B',
    avatar: '👩‍💼',
    description:
      'Manages financial operations, invoicing, payment tracking, and accounting reports',
    capabilities: [
      'invoice_management',
      'payment_tracking',
      'financial_reports',
      'budget_analysis',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'finance_manager'],
      accessibleBy: ['owner', 'admin', 'finance_manager'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 89,
      activeUsers: 2,
      systemHealth: 'optimal',
    },
    quickStats: { value: 12, label: 'Invoices', change: 8.5 },
    dashboardUrl: '/owner/dashboard?tab=theodora',
    apiEndpoints: ['/api/finance', '/api/invoices', '/api/payments'],
  },
  olivia: {
    id: 'olivia',
    name: 'Olivia',
    title: 'Marketing & Brand Manager',
    department: 'marketing',
    icon: 'Megaphone',
    colorScheme: '#EC4899',
    avatar: '👩‍🎨',
    description:
      'Manages marketing campaigns, social media, property listings, and brand communications',
    capabilities: [
      'campaign_management',
      'social_media',
      'listing_optimization',
      'analytics',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'marketing_manager'],
      accessibleBy: ['owner', 'admin', 'marketing_manager'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 234,
      activeUsers: 4,
      systemHealth: 'optimal',
    },
    quickStats: { value: 15, label: 'Campaigns', change: 12.3 },
    dashboardUrl: '/owner/dashboard?tab=olivia',
    apiEndpoints: ['/api/marketing', '/api/campaigns', '/api/social'],
  },
  zoe: {
    id: 'zoe',
    name: 'Zoe',
    title: 'Executive Assistant',
    department: 'executive',
    icon: 'Briefcase',
    colorScheme: '#10B981',
    avatar: '👩‍🏫',
    description:
      'Executive support, calendar management, meeting coordination, and strategic planning assistance',
    capabilities: [
      'calendar_management',
      'meeting_scheduling',
      'task_delegation',
      'executive_reports',
    ],
    permissions: {
      viewableBy: ['owner', 'admin'],
      accessibleBy: ['owner'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 312,
      activeUsers: 1,
      systemHealth: 'optimal',
    },
    quickStats: { value: 8, label: 'Meetings', change: -5.2 },
    dashboardUrl: '/owner/dashboard?tab=zoe',
    apiEndpoints: ['/api/executive', '/api/calendar', '/api/meetings'],
  },
  laila: {
    id: 'laila',
    name: 'Laila',
    title: 'Compliance & Legal Officer',
    department: 'compliance',
    icon: 'Shield',
    colorScheme: '#6366F1',
    avatar: '👩‍⚖️',
    description:
      'Manages regulatory compliance, legal documentation, KYC/AML processes, and contract reviews',
    capabilities: [
      'kyc_verification',
      'aml_monitoring',
      'contract_review',
      'compliance_reports',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'legal_manager'],
      accessibleBy: ['owner', 'admin', 'legal_manager'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 67,
      activeUsers: 2,
      systemHealth: 'optimal',
    },
    quickStats: { value: 5, label: 'Reviews', change: 0 },
    dashboardUrl: '/owner/dashboard?tab=laila',
    apiEndpoints: ['/api/compliance', '/api/legal', '/api/kyc'],
  },
  nadia: {
    id: 'nadia',
    name: 'Nadia',
    title: 'WhatsApp CRM Manager',
    department: 'communications',
    icon: 'MessageSquare',
    colorScheme: '#25D366',
    avatar: '👩‍💼',
    description:
      'Manages 23+ agent WhatsApp numbers, conversation routing, template messaging, and lead pre-qualification',
    capabilities: [
      'conversation_management',
      'lead_scoring',
      'quick_replies',
      'ai_insights',
      'agent_status_monitoring',
      'broadcast_management',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'sales_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 892,
      activeUsers: 6,
      systemHealth: 'optimal',
    },
    quickStats: { value: 47, label: 'Conversations', change: 15.8 },
    dashboardUrl: '/owner/dashboard?tab=nadia',
    apiEndpoints: ['/api/whatsapp', '/api/conversations', '/api/templates'],
  },
  sophia: {
    id: 'sophia',
    name: 'Sophia',
    title: 'Sales Pipeline Manager',
    department: 'sales',
    icon: 'Users',
    colorScheme: '#8B5CF6',
    avatar: '👩‍💻',
    description:
      'Manages sales pipeline, lead assignments, deal tracking, and sales performance analytics',
    capabilities: [
      'pipeline_management',
      'lead_assignment',
      'deal_tracking',
      'sales_forecasting',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'sales_manager', 'agent'],
      accessibleBy: ['owner', 'admin', 'sales_manager'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 456,
      activeUsers: 8,
      systemHealth: 'optimal',
    },
    quickStats: { value: 23, label: 'Active Deals', change: 4.2 },
    dashboardUrl: '/owner/dashboard?tab=sophia',
    apiEndpoints: ['/api/sales', '/api/pipeline', '/api/deals'],
  },
  daisy: {
    id: 'daisy',
    name: 'Daisy',
    title: 'Leasing & Tenant Manager',
    department: 'operations',
    icon: 'Home',
    colorScheme: '#14B8A6',
    avatar: '👩‍🔧',
    description:
      'Manages rental properties, tenant communications, lease agreements, and maintenance requests',
    capabilities: [
      'lease_management',
      'tenant_communications',
      'maintenance_tracking',
      'rental_analytics',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'leasing_manager'],
      accessibleBy: ['owner', 'admin', 'leasing_manager'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 178,
      activeUsers: 5,
      systemHealth: 'optimal',
    },
    quickStats: { value: 156, label: 'Active Leases', change: 2.1 },
    dashboardUrl: '/owner/dashboard?tab=daisy',
    apiEndpoints: ['/api/leasing', '/api/tenants', '/api/maintenance'],
  },
  clara: {
    id: 'clara',
    name: 'Clara',
    title: 'Leads CRM Manager',
    department: 'sales',
    icon: 'Target',
    colorScheme: '#EF4444',
    avatar: '👩‍🎯',
    description:
      'Manages lead pipeline, qualification, nurturing workflows, and conversion tracking',
    capabilities: [
      'lead_management',
      'qualification',
      'nurturing',
      'conversion_tracking',
      'activity_timeline',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'sales_manager', 'agent'],
      accessibleBy: ['owner', 'admin', 'sales_manager'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 234,
      activeUsers: 6,
      systemHealth: 'optimal',
    },
    quickStats: { value: 38, label: 'Active Leads', change: 12.5 },
    dashboardUrl: '/owner/dashboard?tab=clara',
    apiEndpoints: ['/api/leads', '/api/pipeline', '/api/activities'],
  },
  nina: {
    id: 'nina',
    name: 'Nina',
    title: 'WhatsApp Bot Developer',
    department: 'communications',
    icon: 'Bot',
    colorScheme: '#06B6D4',
    avatar: '👩‍💻',
    description:
      'Develops and manages WhatsApp automation bots, conversation flows, and bot analytics',
    capabilities: ['bot_development', 'flow_design', 'session_management', 'analytics'],
    permissions: {
      viewableBy: ['owner', 'admin'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 45,
      activeUsers: 2,
      systemHealth: 'optimal',
    },
    quickStats: { value: 3, label: 'Active Bots', change: 0 },
    dashboardUrl: '/owner/dashboard?tab=nina',
    apiEndpoints: ['/api/bots', '/api/flows', '/api/sessions'],
  },
  nancy: {
    id: 'nancy',
    name: 'Nancy',
    title: 'HR Manager',
    department: 'operations',
    icon: 'Users2',
    colorScheme: '#F97316',
    avatar: '👩‍💼',
    description:
      'Manages employee records, recruitment, performance reviews, and HR operations',
    capabilities: [
      'employee_management',
      'recruitment',
      'performance_tracking',
      'attendance',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'hr_manager'],
      accessibleBy: ['owner', 'admin', 'hr_manager'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 89,
      activeUsers: 3,
      systemHealth: 'optimal',
    },
    quickStats: { value: 24, label: 'Employees', change: 0 },
    dashboardUrl: '/owner/dashboard?tab=nancy',
    apiEndpoints: ['/api/hr', '/api/employees', '/api/recruitment'],
  },
  aurora: {
    id: 'aurora',
    name: 'Aurora',
    title: 'Chief Technology Officer',
    department: 'technology',
    icon: 'Server',
    colorScheme: '#0EA5E9',
    avatar: '👩‍💻',
    description:
      'Oversees all technical operations, system architecture, deployment pipelines, and application portfolio management',
    capabilities: [
      'system_health_monitoring',
      'deployment_pipeline',
      'application_portfolio',
      'performance_analytics',
      'dependency_management',
      'infrastructure_monitoring',
      'mobile_app_management',
      'api_performance_tracking',
    ],
    permissions: {
      viewableBy: ['owner', 'admin'],
      accessibleBy: ['owner'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 234,
      activeUsers: 2,
      systemHealth: 'optimal',
    },
    quickStats: { value: 99.98, label: 'Uptime %', change: 0.02 },
    dashboardUrl: '/owner/dashboard?tab=aurora',
    apiEndpoints: ['/api/system', '/api/deployments', '/api/applications'],
    techStack: {
      frontend: ['React 18', 'Redux Toolkit', 'Vite'],
      backend: ['Node.js 20', 'Express', 'MongoDB 7'],
      database: ['MongoDB', 'Redis'],
      infrastructure: ['Replit', 'MongoDB Atlas'],
    },
    systemModules: {
      applicationPortfolio: true,
      developmentLifecycle: true,
      systemHealthMonitor: true,
      deploymentPipeline: true,
      apiPerformance: true,
    },
  },
  hazel: {
    id: 'hazel',
    name: 'Hazel',
    title: 'Elite Frontend Engineer',
    department: 'technology',
    icon: 'Palette',
    colorScheme: '#F472B6',
    avatar: '👩‍🎨',
    description:
      'Designs and builds pixel-perfect UI components, maintains the design system, and ensures accessibility compliance across all interfaces',
    capabilities: [
      'component_library',
      'design_system',
      'responsive_design',
      'accessibility_audit',
      'ui_performance',
      'animation_system',
      'theme_management',
    ],
    permissions: {
      viewableBy: ['owner', 'admin'],
      accessibleBy: ['owner'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 178,
      activeUsers: 2,
      systemHealth: 'optimal',
    },
    quickStats: { value: 47, label: 'Components', change: 3.2 },
    dashboardUrl: '/owner/dashboard?tab=hazel',
    apiEndpoints: ['/api/frontend', '/api/components', '/api/design-system'],
    designMetrics: {
      componentCount: 47,
      accessibilityScore: 98,
      lighthouseScore: 94,
      bundleSize: '7.9 MB',
    },
  },
  willow: {
    id: 'willow',
    name: 'Willow',
    title: 'Elite Backend Engineer',
    department: 'technology',
    icon: 'Database',
    colorScheme: '#22C55E',
    avatar: '👨‍💻',
    description:
      'Architects backend services, optimizes database queries, manages API performance, and ensures system reliability and scalability',
    capabilities: [
      'api_development',
      'database_optimization',
      'caching_strategies',
      'websocket_realtime',
      'data_pipeline',
      'security_hardening',
      'load_balancing',
    ],
    permissions: {
      viewableBy: ['owner', 'admin'],
      accessibleBy: ['owner'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 156,
      activeUsers: 2,
      systemHealth: 'optimal',
    },
    quickStats: { value: 45, label: 'APIs', change: 2.1 },
    dashboardUrl: '/owner/dashboard?tab=willow',
    apiEndpoints: ['/api/backend', '/api/performance', '/api/database'],
    backendMetrics: {
      apiCount: 45,
      avgResponseTime: 89,
      cacheHitRate: 94.5,
      dbConnections: 12,
    },
  },
  evangeline: {
    id: 'evangeline',
    name: 'Evangeline',
    title: 'Legal Risk Analyst',
    department: 'legal',
    icon: 'Scale',
    colorScheme: '#E31E24',
    avatar: '👩‍⚖️',
    description:
      'Proactively identifies, documents, and helps resolve legal issues. Monitors contracts, regulations, and transaction compliance',
    capabilities: [
      'legal_risk_analysis',
      'contract_monitoring',
      'regulatory_tracking',
      'dispute_prevention',
      'best_practices_library',
      'due_diligence',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'legal_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 45,
      activeUsers: 2,
      systemHealth: 'optimal',
    },
    quickStats: { value: 12, label: 'Reviews', change: 3.5 },
    dashboardUrl: '/owner/dashboard?tab=evangeline',
    apiEndpoints: ['/api/legal', '/api/risks', '/api/contracts'],
  },
  sentinel: {
    id: 'sentinel',
    name: 'Sentinel',
    title: 'Property Monitoring AI',
    department: 'operations',
    icon: 'Eye',
    colorScheme: '#7C3AED',
    avatar: '🛡️',
    description:
      'IoT integration for property condition monitoring, predictive maintenance scheduling, and emergency response coordination',
    capabilities: [
      'iot_monitoring',
      'predictive_maintenance',
      'inspection_scheduling',
      'vendor_management',
      'emergency_response',
      'property_health_tracking',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'operations_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 89,
      activeUsers: 3,
      systemHealth: 'optimal',
    },
    quickStats: { value: 156, label: 'Properties', change: 0 },
    dashboardUrl: '/owner/dashboard?tab=sentinel',
    apiEndpoints: ['/api/monitoring', '/api/maintenance', '/api/inspections'],
  },
  hunter: {
    id: 'hunter',
    name: 'Hunter',
    title: 'Lead Prospecting AI',
    department: 'sales',
    icon: 'Search',
    colorScheme: '#0D9488',
    avatar: '🎯',
    description:
      'Scrapes and analyzes potential client databases, identifies property buying/selling patterns, and manages automated outreach',
    capabilities: [
      'prospect_analysis',
      'market_scanning',
      'pattern_detection',
      'outreach_automation',
      'lead_enrichment',
      'competitor_tracking',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'sales_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 67,
      activeUsers: 2,
      systemHealth: 'optimal',
    },
    quickStats: { value: 34, label: 'Prospects', change: 8.2 },
    dashboardUrl: '/owner/dashboard?tab=hunter',
    apiEndpoints: ['/api/prospecting', '/api/outreach', '/api/enrichment'],
  },
};

// ============================================================================
// DEPARTMENT COLORS
// ============================================================================

export const DEPARTMENT_COLORS: Record<string, string> = {
  operations: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  finance: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
  marketing: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
  executive: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
  compliance: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
  communications: 'linear-gradient(135deg, #25D366 0%, #128C7E 100%)',
  sales: 'linear-gradient(135deg, #8B5CF6 0%, #D946EF 100%)',
  technology: 'linear-gradient(135deg, #0EA5E9 0%, #06B6D4 100%)',
  legal: 'linear-gradient(135deg, #E31E24 0%, #C62828 100%)',
};

// ============================================================================
// SEED DATA GENERATORS
// ============================================================================

export const generateActivities = (): Activity[] => {
  const now = Date.now();
  return [
    {
      id: 1,
      assistantId: 'nadia',
      action: 'New lead captured from WhatsApp',
      target: 'Ahmed Al-Rashid',
      timestamp: new Date(now - 300000).toISOString(),
      type: 'success',
    },
    {
      id: 2,
      assistantId: 'clara',
      action: 'Lead stage updated to Qualified',
      target: 'Sarah Johnson',
      timestamp: new Date(now - 600000).toISOString(),
      type: 'success',
    },
    {
      id: 3,
      assistantId: 'mary',
      action: 'Property data imported',
      target: '23 new units from Excel',
      timestamp: new Date(now - 900000).toISOString(),
      type: 'success',
    },
    {
      id: 4,
      assistantId: 'theodora',
      action: 'Invoice generated',
      target: 'INV-2024-0156',
      timestamp: new Date(now - 1200000).toISOString(),
      type: 'info',
    },
    {
      id: 5,
      assistantId: 'sophia',
      action: 'Deal closed successfully',
      target: 'Villa 348 - AED 2.5M',
      timestamp: new Date(now - 1500000).toISOString(),
      type: 'success',
    },
    {
      id: 6,
      assistantId: 'nancy',
      action: 'Interview scheduled',
      target: 'Mohammed Ali - Sales Agent',
      timestamp: new Date(now - 1800000).toISOString(),
      type: 'pending',
    },
    {
      id: 7,
      assistantId: 'laila',
      action: 'KYC verification completed',
      target: 'James Wilson',
      timestamp: new Date(now - 2100000).toISOString(),
      type: 'success',
    },
    {
      id: 8,
      assistantId: 'nina',
      action: 'Bot session started',
      target: 'Lion0 WhatsApp Bot',
      timestamp: new Date(now - 2400000).toISOString(),
      type: 'active',
    },
    {
      id: 9,
      assistantId: 'daisy',
      action: 'Lease renewal processed',
      target: 'Unit 156 - Palm Views',
      timestamp: new Date(now - 2700000).toISOString(),
      type: 'success',
    },
    {
      id: 10,
      assistantId: 'olivia',
      action: 'Campaign launched',
      target: 'Summer Property Showcase',
      timestamp: new Date(now - 3000000).toISOString(),
      type: 'success',
    },
    {
      id: 11,
      assistantId: 'aurora',
      action: 'System health check completed',
      target: 'All services healthy',
      timestamp: new Date(now - 3300000).toISOString(),
      type: 'success',
    },
    {
      id: 12,
      assistantId: 'aurora',
      action: 'Deployment successful',
      target: 'WhatsApp CRM v2.4.1',
      timestamp: new Date(now - 3600000).toISOString(),
      type: 'success',
    },
  ];
};

export const generateNotifications = (): Record<string, Notification[]> => {
  const now = Date.now();
  return {
    nadia: [
      {
        id: 'n1',
        type: 'lead',
        message: 'New lead from WhatsApp',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 120000).toISOString(),
      },
      {
        id: 'n2',
        type: 'task',
        message: 'Agent quota exceeded',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 300000).toISOString(),
      },
    ],
    clara: [
      {
        id: 'n3',
        type: 'lead',
        message: 'Lead requires follow-up',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 180000).toISOString(),
      },
    ],
    theodora: [
      {
        id: 'n4',
        type: 'payment',
        message: 'Invoice overdue',
        severity: 'critical',
        isRead: false,
        timestamp: new Date(now - 240000).toISOString(),
      },
    ],
    mary: [],
    nina: [
      {
        id: 'n5',
        type: 'bot',
        message: 'Bot session expired',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 360000).toISOString(),
      },
    ],
    nancy: [],
    sophia: [
      {
        id: 'n6',
        type: 'deal',
        message: 'Deal awaiting approval',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 420000).toISOString(),
      },
    ],
    daisy: [],
    olivia: [],
    zoe: [
      {
        id: 'n7',
        type: 'meeting',
        message: 'Meeting in 30 minutes',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 60000).toISOString(),
      },
    ],
    laila: [],
    aurora: [],
    hazel: [],
    willow: [],
  };
};

export const generateTasks = (): Record<string, Task[]> => ({
  nadia: [
    {
      id: 't1',
      title: 'Review unassigned conversations',
      priority: 'high',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
  ],
  clara: [
    {
      id: 't2',
      title: 'Follow up with hot leads',
      priority: 'high',
      status: 'in_progress',
      assignedTo: 'agent_1',
      dueDate: new Date().toISOString(),
    },
  ],
  theodora: [
    {
      id: 't3',
      title: 'Process pending invoices',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
  ],
  mary: [],
  nina: [],
  nancy: [],
  sophia: [],
  daisy: [],
  olivia: [],
  zoe: [],
  laila: [],
  aurora: [],
  hazel: [],
  willow: [],
});
