// ============================================================================
// AI ASSISTANT DASHBOARD — REGISTRY DATA & SEED GENERATORS
// Extracted from aiAssistantDashboardSlice.tsx for maintainability
// ============================================================================

import type { AIAssistant, Activity, Notification, Task } from './types';

// ============================================================================
// AI ASSISTANTS REGISTRY
// ============================================================================

export const AI_ASSISTANTS_REGISTRY: Record<string, AIAssistant> = {
  mary: {
    id: 'mary',
    name: 'Mary',
    title: 'Inventory & Data Manager',
    department: 'operations',
    icon: 'FileText',
    colorScheme: '#3B82F6',
    avatar: '👩‍💻',
    description:
      'Manages DAMAC Hills 2 property inventory with 9,378+ units, data acquisition tools, and asset management',
    capabilities: [
      'property_crud',
      'data_tools',
      'asset_fetcher',
      'filtering',
      'excel_import',
      'ocr_extraction',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'sales_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 156,
      activeUsers: 3,
      systemHealth: 'optimal',
    },
    quickStats: { value: 9378, label: 'Properties', change: 0 },
    dashboardUrl: '/owner/dashboard?tab=mary',
    apiEndpoints: ['/api/inventory', '/api/properties', '/api/assets'],
  },
  theodora: {
    id: 'theodora',
    name: 'Theodora',
    title: 'Finance & Accounts Director',
    department: 'finance',
    icon: 'DollarSign',
    colorScheme: '#F59E0B',
    avatar: '👩‍💼',
    description:
      'Manages financial operations, invoicing, payment tracking, and accounting reports',
    capabilities: [
      'invoice_management',
      'payment_tracking',
      'financial_reports',
      'budget_analysis',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'finance_manager'],
      accessibleBy: ['owner', 'admin', 'finance_manager'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 89,
      activeUsers: 2,
      systemHealth: 'optimal',
    },
    quickStats: { value: 12, label: 'Invoices', change: 8.5 },
    dashboardUrl: '/owner/dashboard?tab=theodora',
    apiEndpoints: ['/api/finance', '/api/invoices', '/api/payments'],
  },
  olivia: {
    id: 'olivia',
    name: 'Olivia',
    title: 'Marketing & Brand Manager',
    department: 'marketing',
    icon: 'Megaphone',
    colorScheme: '#EC4899',
    avatar: '👩‍🎨',
    description:
      'Manages marketing campaigns, social media, property listings, and brand communications',
    capabilities: ['campaign_management', 'social_media', 'listing_optimization', 'analytics'],
    permissions: {
      viewableBy: ['owner', 'admin', 'marketing_manager'],
      accessibleBy: ['owner', 'admin', 'marketing_manager'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 234,
      activeUsers: 4,
      systemHealth: 'optimal',
    },
    quickStats: { value: 15, label: 'Campaigns', change: 12.3 },
    dashboardUrl: '/owner/dashboard?tab=olivia',
    apiEndpoints: ['/api/marketing', '/api/campaigns', '/api/social'],
  },
  zoe: {
    id: 'zoe',
    name: 'Zoe',
    title: 'Executive Assistant',
    department: 'executive',
    icon: 'Briefcase',
    colorScheme: '#10B981',
    avatar: '👩‍🏫',
    description:
      'Executive support, calendar management, meeting coordination, and strategic planning assistance',
    capabilities: [
      'calendar_management',
      'meeting_scheduling',
      'task_delegation',
      'executive_reports',
    ],
    permissions: {
      viewableBy: ['owner', 'admin'],
      accessibleBy: ['owner'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 312,
      activeUsers: 1,
      systemHealth: 'optimal',
    },
    quickStats: { value: 8, label: 'Meetings', change: -5.2 },
    dashboardUrl: '/owner/dashboard?tab=zoe',
    apiEndpoints: ['/api/executive', '/api/calendar', '/api/meetings'],
  },
  laila: {
    id: 'laila',
    name: 'Laila',
    title: 'Compliance & Legal Officer',
    department: 'compliance',
    icon: 'Shield',
    colorScheme: '#6366F1',
    avatar: '👩‍⚖️',
    description:
      'Manages regulatory compliance, legal documentation, KYC/AML processes, and contract reviews',
    capabilities: ['kyc_verification', 'aml_monitoring', 'contract_review', 'compliance_reports'],
    permissions: {
      viewableBy: ['owner', 'admin', 'legal_manager'],
      accessibleBy: ['owner', 'admin', 'legal_manager'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 67,
      activeUsers: 2,
      systemHealth: 'optimal',
    },
    quickStats: { value: 5, label: 'Reviews', change: 0 },
    dashboardUrl: '/owner/dashboard?tab=laila',
    apiEndpoints: ['/api/compliance', '/api/legal', '/api/kyc'],
  },
  nadia: {
    id: 'nadia',
    name: 'Nadia',
    title: 'WhatsApp Business CRM Manager',
    department: 'communications',
    icon: 'MessageSquare',
    colorScheme: '#25D366',
    avatar: '👩‍💼',
    description:
      'Enterprise CRM for 23+ agent WhatsApp numbers with message templates, lead assignment, broadcast campaigns, and comprehensive analytics',
    capabilities: [
      'cloud_api_integration',
      'webhook_message_handling',
      'message_templates',
      'multi_agent_coordination',
      'lead_assignment',
      'broadcast_messaging',
      'crm_analytics',
      'compliance_tracking',
      'payment_integration',
      'conversation_archive',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'sales_manager', 'agent'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 892,
      activeUsers: 6,
      systemHealth: 'optimal',
    },
    quickStats: { value: 47, label: 'Active Conversations', change: 15.8 },
    dashboardUrl: '/owner/dashboard?tab=nadia',
    apiEndpoints: [
      '/api/nadia/messages/send',
      '/api/nadia/messages/send-template',
      '/api/nadia/webhooks',
      '/api/nadia/conversations',
      '/api/nadia/templates',
      '/api/nadia/phone-numbers',
      '/api/nadia/leads',
      '/api/nadia/broadcasts',
      '/api/nadia/analytics',
    ],
  },
  linda: {
    id: 'linda',
    name: 'Linda',
    title: 'WhatsApp LocalAuth Bot Manager',
    department: 'communications',
    icon: 'Smartphone',
    colorScheme: '#8B5CF6',
    avatar: '🤖',
    description:
      'Manages agent-side WhatsApp sessions with LocalAuth, real estate command execution, contact sync, and AI opportunity scoring',
    capabilities: [
      'local_auth_management',
      'multi_account_coordination',
      'qr_device_linking',
      'contact_sync_import',
      'ai_opportunity_scoring',
      'command_execution',
      'conversation_routing',
      'session_recovery',
      'group_management',
      'reaction_tracking',
      'openclaw_gateway',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'agent'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 0,
      activeUsers: 0,
      systemHealth: 'optimal',
    },
    quickStats: { value: 0, label: 'Active Sessions', change: 0 },
    dashboardUrl: '/owner/dashboard?tab=linda',
    apiEndpoints: [
      '/api/linda/status',
      '/api/linda/qr-generate',
      '/api/linda/sessions',
      '/api/linda/send-message',
      '/api/linda/contacts',
      '/api/linda/commands',
      '/api/linda/analytics',
    ],
  },
  sophia: {
    id: 'sophia',
    name: 'Sophia',
    title: 'Sales Pipeline Manager',
    department: 'sales',
    icon: 'Users',
    colorScheme: '#8B5CF6',
    avatar: '👩‍💻',
    description:
      'Manages sales pipeline, lead assignments, deal tracking, and sales performance analytics',
    capabilities: ['pipeline_management', 'lead_assignment', 'deal_tracking', 'sales_forecasting'],
    permissions: {
      viewableBy: ['owner', 'admin', 'sales_manager', 'agent'],
      accessibleBy: ['owner', 'admin', 'sales_manager'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 456,
      activeUsers: 8,
      systemHealth: 'optimal',
    },
    quickStats: { value: 23, label: 'Active Deals', change: 4.2 },
    dashboardUrl: '/owner/dashboard?tab=sophia',
    apiEndpoints: ['/api/sales', '/api/pipeline', '/api/deals'],
  },
  daisy: {
    id: 'daisy',
    name: 'Daisy',
    title: 'Leasing & Tenant Manager',
    department: 'operations',
    icon: 'Home',
    colorScheme: '#14B8A6',
    avatar: '👩‍🔧',
    description:
      'Manages rental properties, tenant communications, lease agreements, and maintenance requests',
    capabilities: [
      'lease_management',
      'tenant_communications',
      'maintenance_tracking',
      'rental_analytics',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'leasing_manager'],
      accessibleBy: ['owner', 'admin', 'leasing_manager'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 178,
      activeUsers: 5,
      systemHealth: 'optimal',
    },
    quickStats: { value: 156, label: 'Active Leases', change: 2.1 },
    dashboardUrl: '/owner/dashboard?tab=daisy',
    apiEndpoints: ['/api/leasing', '/api/tenants', '/api/maintenance'],
  },
  clara: {
    id: 'clara',
    name: 'Clara',
    title: 'Leads CRM Manager',
    department: 'sales',
    icon: 'Target',
    colorScheme: '#EF4444',
    avatar: '👩‍🎯',
    description:
      'Manages lead pipeline, qualification, nurturing workflows, and conversion tracking',
    capabilities: [
      'lead_management',
      'qualification',
      'nurturing',
      'conversion_tracking',
      'activity_timeline',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'sales_manager', 'agent'],
      accessibleBy: ['owner', 'admin', 'sales_manager'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 234,
      activeUsers: 6,
      systemHealth: 'optimal',
    },
    quickStats: { value: 38, label: 'Active Leads', change: 12.5 },
    dashboardUrl: '/owner/dashboard?tab=clara',
    apiEndpoints: ['/api/leads', '/api/pipeline', '/api/activities'],
  },
  nina: {
    id: 'nina',
    name: 'Nina',
    title: 'WhatsApp Bot Developer & Flow Designer',
    department: 'communications',
    icon: 'Bot',
    colorScheme: '#06B6D4',
    avatar: '🧠',
    description:
      'Designs conversation flows with NLP intent recognition, slot filling, multi-turn dialogue, and bot analytics for real estate inquiries',
    capabilities: [
      'flow_builder',
      'nlp_intent_recognition',
      'slot_filling',
      'multi_turn_dialogue',
      'entity_extraction',
      'flow_versioning',
      'bot_analytics',
      'conversation_recovery',
      'custom_node_types',
      'flow_testing',
    ],
    permissions: {
      viewableBy: ['owner', 'admin'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 45,
      activeUsers: 2,
      systemHealth: 'optimal',
    },
    quickStats: { value: 3, label: 'Active Bots', change: 0 },
    dashboardUrl: '/owner/dashboard?tab=nina',
    apiEndpoints: [
      '/api/nina/flows',
      '/api/nina/flows/:id/versions',
      '/api/nina/flows/:id/test',
      '/api/nina/nlp/intent',
      '/api/nina/nlp/slots',
      '/api/nina/bots',
      '/api/nina/analytics/flows',
      '/api/nina/analytics/intents',
    ],
  },
  nancy: {
    id: 'nancy',
    name: 'Nancy',
    title: 'HR Manager',
    department: 'operations',
    icon: 'Users2',
    colorScheme: '#F97316',
    avatar: '👩‍💼',
    description: 'Manages employee records, recruitment, performance reviews, and HR operations',
    capabilities: ['employee_management', 'recruitment', 'performance_tracking', 'attendance'],
    permissions: {
      viewableBy: ['owner', 'admin', 'hr_manager'],
      accessibleBy: ['owner', 'admin', 'hr_manager'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 89,
      activeUsers: 3,
      systemHealth: 'optimal',
    },
    quickStats: { value: 24, label: 'Employees', change: 0 },
    dashboardUrl: '/owner/dashboard?tab=nancy',
    apiEndpoints: ['/api/hr', '/api/employees', '/api/recruitment'],
  },
  aurora: {
    id: 'aurora',
    name: 'Aurora',
    title: 'Chief Technology Officer',
    department: 'technology',
    icon: 'Server',
    colorScheme: '#0EA5E9',
    avatar: '👩‍💻',
    description:
      'Oversees all technical operations, system architecture, deployment pipelines, and application portfolio management',
    capabilities: [
      'system_health_monitoring',
      'deployment_pipeline',
      'application_portfolio',
      'performance_analytics',
      'dependency_management',
      'infrastructure_monitoring',
      'mobile_app_management',
      'api_performance_tracking',
    ],
    permissions: {
      viewableBy: ['owner', 'admin'],
      accessibleBy: ['owner'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 234,
      activeUsers: 2,
      systemHealth: 'optimal',
    },
    quickStats: { value: 99.98, label: 'Uptime %', change: 0.02 },
    dashboardUrl: '/owner/dashboard?tab=aurora',
    apiEndpoints: ['/api/system', '/api/deployments', '/api/applications'],
    techStack: {
      frontend: ['React 18', 'Redux Toolkit', 'Vite'],
      backend: ['Node.js 20', 'Express', 'MongoDB 7'],
      database: ['MongoDB', 'Redis'],
      infrastructure: ['Replit', 'MongoDB Atlas'],
    },
    systemModules: {
      applicationPortfolio: true,
      developmentLifecycle: true,
      systemHealthMonitor: true,
      deploymentPipeline: true,
      apiPerformance: true,
    },
  },
  hazel: {
    id: 'hazel',
    name: 'Hazel',
    title: 'Elite Frontend Engineer',
    department: 'technology',
    icon: 'Palette',
    colorScheme: '#F472B6',
    avatar: '👩‍🎨',
    description:
      'Designs and builds pixel-perfect UI components, maintains the design system, and ensures accessibility compliance across all interfaces',
    capabilities: [
      'component_library',
      'design_system',
      'responsive_design',
      'accessibility_audit',
      'ui_performance',
      'animation_system',
      'theme_management',
    ],
    permissions: {
      viewableBy: ['owner', 'admin'],
      accessibleBy: ['owner'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 178,
      activeUsers: 2,
      systemHealth: 'optimal',
    },
    quickStats: { value: 47, label: 'Components', change: 3.2 },
    dashboardUrl: '/owner/dashboard?tab=hazel',
    apiEndpoints: ['/api/frontend', '/api/components', '/api/design-system'],
    designMetrics: {
      componentCount: 47,
      accessibilityScore: 98,
      lighthouseScore: 94,
      bundleSize: '7.9 MB',
    },
  },
  willow: {
    id: 'willow',
    name: 'Willow',
    title: 'Elite Backend Engineer',
    department: 'technology',
    icon: 'Database',
    colorScheme: '#22C55E',
    avatar: '👨‍💻',
    description:
      'Architects backend services, optimizes database queries, manages API performance, and ensures system reliability and scalability',
    capabilities: [
      'api_development',
      'database_optimization',
      'caching_strategies',
      'websocket_realtime',
      'data_pipeline',
      'security_hardening',
      'load_balancing',
    ],
    permissions: {
      viewableBy: ['owner', 'admin'],
      accessibleBy: ['owner'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 156,
      activeUsers: 2,
      systemHealth: 'optimal',
    },
    quickStats: { value: 45, label: 'APIs', change: 2.1 },
    dashboardUrl: '/owner/dashboard?tab=willow',
    apiEndpoints: ['/api/backend', '/api/performance', '/api/database'],
    backendMetrics: {
      apiCount: 45,
      avgResponseTime: 89,
      cacheHitRate: 94.5,
      dbConnections: 12,
    },
  },
  evangeline: {
    id: 'evangeline',
    name: 'Evangeline',
    title: 'Legal Risk Analyst',
    department: 'legal',
    icon: 'Scale',
    colorScheme: '#D4AF37',
    avatar: '👩‍⚖️',
    description:
      'Proactively identifies, documents, and helps resolve legal issues. Monitors contracts, regulations, and transaction compliance',
    capabilities: [
      'legal_risk_analysis',
      'contract_monitoring',
      'regulatory_tracking',
      'dispute_prevention',
      'best_practices_library',
      'due_diligence',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'legal_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 45,
      activeUsers: 2,
      systemHealth: 'optimal',
    },
    quickStats: { value: 12, label: 'Reviews', change: 3.5 },
    dashboardUrl: '/owner/dashboard?tab=evangeline',
    apiEndpoints: ['/api/legal', '/api/risks', '/api/contracts'],
  },
  sentinel: {
    id: 'sentinel',
    name: 'Sentinel',
    title: 'Property Monitoring AI',
    department: 'operations',
    icon: 'Eye',
    colorScheme: '#7C3AED',
    avatar: '🛡️',
    description:
      'IoT integration for property condition monitoring, predictive maintenance scheduling, and emergency response coordination',
    capabilities: [
      'iot_monitoring',
      'predictive_maintenance',
      'inspection_scheduling',
      'vendor_management',
      'emergency_response',
      'property_health_tracking',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'operations_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 89,
      activeUsers: 3,
      systemHealth: 'optimal',
    },
    quickStats: { value: 156, label: 'Properties', change: 0 },
    dashboardUrl: '/owner/dashboard?tab=sentinel',
    apiEndpoints: ['/api/monitoring', '/api/maintenance', '/api/inspections'],
  },
  hunter: {
    id: 'hunter',
    name: 'Hunter',
    title: 'Lead Prospecting AI',
    department: 'sales',
    icon: 'Search',
    colorScheme: '#0D9488',
    avatar: '🎯',
    description:
      'Scrapes and analyzes potential client databases, identifies property buying/selling patterns, and manages automated outreach',
    capabilities: [
      'prospect_analysis',
      'market_scanning',
      'pattern_detection',
      'outreach_automation',
      'lead_enrichment',
      'competitor_tracking',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'sales_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 67,
      activeUsers: 2,
      systemHealth: 'optimal',
    },
    quickStats: { value: 34, label: 'Prospects', change: 8.2 },
    dashboardUrl: '/owner/dashboard?tab=hunter',
    apiEndpoints: ['/api/prospecting', '/api/outreach', '/api/enrichment'],
  },
  henry: {
    id: 'henry',
    name: 'Henry',
    title: 'Record Keeper & Timeline Master',
    department: 'technology',
    icon: 'BookOpen',
    colorScheme: '#7C3AED',
    avatar: '📚',
    description:
      'Centralized memory and audit system. Creates immutable audit trails, enables cross-system analytics, provides operational clarity, and automates compliance reporting',
    capabilities: [
      'universal_event_ingestion',
      'intelligent_categorization',
      'timeline_visualization',
      'relationship_mapping',
      'search_query_engine',
      'sla_monitoring',
      'compliance_logging',
      'anomaly_detection',
    ],
    permissions: {
      viewableBy: ['owner', 'admin'],
      accessibleBy: ['owner'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 412,
      activeUsers: 1,
      systemHealth: 'optimal',
    },
    quickStats: { value: 8921, label: 'Events Logged', change: 1.2 },
    dashboardUrl: '/owner/dashboard?tab=henry',
    apiEndpoints: ['/api/events', '/api/timeline', '/api/audit', '/api/reports'],
  },
  cipher: {
    id: 'cipher',
    name: 'Cipher',
    title: 'Predictive Market Analyst',
    department: 'intelligence',
    icon: 'LineChart',
    colorScheme: '#0D9488',
    avatar: '🔮',
    description:
      'Uses advanced analytics on DLD transaction data, news, and economic indicators to generate predictive reports on neighborhood trends and property valuation',
    capabilities: [
      'market_trend_analysis',
      'price_prediction',
      'demand_forecasting',
      'competitor_tracking',
      'investment_scoring',
      'economic_indicator_monitoring',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'investment_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 156,
      activeUsers: 3,
      systemHealth: 'optimal',
    },
    quickStats: { value: 94.2, label: 'Prediction Accuracy %', change: 0.5 },
    dashboardUrl: '/owner/dashboard?tab=cipher',
    apiEndpoints: ['/api/analytics', '/api/predictions', '/api/market-data'],
  },
  atlas: {
    id: 'atlas',
    name: 'Atlas',
    title: 'Development & Project Intelligence',
    department: 'intelligence',
    icon: 'Map',
    colorScheme: '#6366F1',
    avatar: '🗺️',
    description:
      'Analyzes zoning, DLD master plans, market gaps, and developer track records to identify high-potential off-plan projects',
    capabilities: [
      'feasibility_analysis',
      'zoning_analysis',
      'developer_tracking',
      'project_pipeline',
      'market_gap_detection',
      'roi_projection',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'investment_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 89,
      activeUsers: 2,
      systemHealth: 'optimal',
    },
    quickStats: { value: 47, label: 'Projects Tracked', change: 3.1 },
    dashboardUrl: '/owner/dashboard?tab=atlas',
    apiEndpoints: ['/api/projects', '/api/developers', '/api/feasibility'],
  },
  vesta: {
    id: 'vesta',
    name: 'Vesta',
    title: 'Project & Snagging Coordinator',
    department: 'operations',
    icon: 'ClipboardCheck',
    colorScheme: '#F97316',
    avatar: '🏗️',
    description:
      'Tracks construction milestones for off-plan buyers, automates developer communication, and manages the digital snagging process',
    capabilities: [
      'milestone_tracking',
      'developer_communication',
      'snagging_management',
      'defect_reporting',
      'handover_coordination',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'operations_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 64,
      activeUsers: 3,
      systemHealth: 'optimal',
    },
    quickStats: { value: 23, label: 'Active Projects', change: 2.0 },
    dashboardUrl: '/owner/dashboard?tab=vesta',
    apiEndpoints: ['/api/construction', '/api/snagging', '/api/handover'],
  },
  juno: {
    id: 'juno',
    name: 'Juno',
    title: 'Smart Community & Facilities Manager',
    department: 'operations',
    icon: 'Building',
    colorScheme: '#14B8A6',
    avatar: '🏢',
    description:
      'Integrates with building IoT systems for energy optimization, manages community events, and automates facility service requests',
    capabilities: [
      'iot_integration',
      'energy_optimization',
      'event_management',
      'service_automation',
      'access_control',
      'utility_monitoring',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'operations_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 201,
      activeUsers: 4,
      systemHealth: 'optimal',
    },
    quickStats: { value: 12, label: 'Buildings Managed', change: 0 },
    dashboardUrl: '/owner/dashboard?tab=juno',
    apiEndpoints: ['/api/facilities', '/api/iot', '/api/community'],
  },
  kairos: {
    id: 'kairos',
    name: 'Kairos',
    title: 'Luxury Concierge & VIP Experience',
    department: 'customer_experience',
    icon: 'Crown',
    colorScheme: '#D97706',
    avatar: '👑',
    description:
      'Curates personalized services for high-net-worth clients: viewing schedules, interior design partners, visa and payment coordination',
    capabilities: [
      'vip_client_management',
      'concierge_services',
      'lifestyle_coordination',
      'partner_network',
      'exclusive_access',
      'personalized_experience',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'luxury_sales_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 38,
      activeUsers: 2,
      systemHealth: 'optimal',
    },
    quickStats: { value: 11, label: 'VIP Clients', change: 1.5 },
    dashboardUrl: '/owner/dashboard?tab=kairos',
    apiEndpoints: ['/api/concierge', '/api/vip', '/api/lifestyle'],
  },
  maven: {
    id: 'maven',
    name: 'Maven',
    title: 'Investment Strategy & Portfolio Optimizer',
    department: 'finance',
    icon: 'PieChart',
    colorScheme: '#8B5CF6',
    avatar: '📊',
    description:
      'Analyzes rental yields, capital appreciation trends, and tax implications to provide data-driven investment advice',
    capabilities: [
      'portfolio_analysis',
      'yield_optimization',
      'tax_planning',
      'investment_recommendations',
      'risk_assessment',
      'performance_tracking',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'investment_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 74,
      activeUsers: 2,
      systemHealth: 'optimal',
    },
    quickStats: { value: 7.8, label: 'Avg Yield %', change: 0.3 },
    dashboardUrl: '/owner/dashboard?tab=maven',
    apiEndpoints: ['/api/portfolio', '/api/investments', '/api/yields'],
  },
  archer: {
    id: 'archer',
    name: 'Archer',
    title: 'Lead Scoring Engine',
    department: 'sales',
    icon: 'Target',
    colorScheme: '#EF4444',
    avatar: '🎯',
    description:
      'Calculates lead conversion probability scores (0–100) using enquiry source, budget signals, area preference, and engagement history',
    capabilities: [
      'lead_scoring',
      'conversion_prediction',
      'engagement_tracking',
      'budget_analysis',
      'priority_ranking',
      'pipeline_optimization',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'sales_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 890,
      activeUsers: 5,
      systemHealth: 'optimal',
    },
    quickStats: { value: 78, label: 'Avg Score', change: 2.4 },
    dashboardUrl: '/owner/dashboard?tab=archer',
    apiEndpoints: ['/api/leads/:id/score', '/api/scoring/rules', '/api/scoring/history'],
  },
  prism: {
    id: 'prism',
    name: 'Prism',
    title: 'AI Property Matching Engine',
    department: 'sales',
    icon: 'Layers',
    colorScheme: '#0EA5E9',
    avatar: '🔭',
    description:
      'Matches buyer and tenant requirements to the best-fit properties using vector similarity search across the full inventory',
    capabilities: [
      'requirement_parsing',
      'vector_similarity_search',
      'inventory_matching',
      'ranked_recommendations',
      'preference_learning',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'sales_manager', 'agent'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 234,
      activeUsers: 6,
      systemHealth: 'optimal',
    },
    quickStats: { value: 93, label: 'Match Accuracy %', change: 1.2 },
    dashboardUrl: '/owner/dashboard?tab=prism',
    apiEndpoints: [
      '/api/matching/properties',
      '/api/matching/preferences',
      '/api/matching/history',
    ],
  },
  sage: {
    id: 'sage',
    name: 'Sage',
    title: 'Mortgage & Financing Advisor',
    department: 'finance',
    icon: 'Calculator',
    colorScheme: '#14B8A6',
    avatar: '💰',
    description:
      'Provides mortgage eligibility calculations, EIBOR rate tracking, bank comparison, and financing pathway guidance',
    capabilities: [
      'mortgage_calculation',
      'eligibility_assessment',
      'rate_comparison',
      'bank_referrals',
      'affordability_analysis',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'sales_manager', 'agent'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 167,
      activeUsers: 4,
      systemHealth: 'optimal',
    },
    quickStats: { value: 167, label: 'Calculations Run', change: 5.6 },
    dashboardUrl: '/owner/dashboard?tab=sage',
    apiEndpoints: ['/api/finance/mortgage-calc', '/api/finance/rates', '/api/finance/banks'],
  },
  echo: {
    id: 'echo',
    name: 'Echo',
    title: 'Client Communication History & Timeline',
    department: 'customer_experience',
    icon: 'Clock',
    colorScheme: '#6366F1',
    avatar: '📜',
    description:
      'Maintains a full, searchable communication timeline per client across WhatsApp, email, calls, and meetings',
    capabilities: [
      'timeline_management',
      'cross_channel_aggregation',
      'communication_search',
      'context_retrieval',
      'thread_linking',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'sales_manager', 'agent'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 2341,
      activeUsers: 8,
      systemHealth: 'optimal',
    },
    quickStats: { value: 2341, label: 'Messages Indexed', change: 4.1 },
    dashboardUrl: '/owner/dashboard?tab=echo',
    apiEndpoints: ['/api/cx/timeline/:clientId', '/api/cx/communications', '/api/cx/search'],
  },
  mira: {
    id: 'mira',
    name: 'Mira',
    title: 'Multilingual Translation Engine',
    department: 'customer_experience',
    icon: 'Globe',
    colorScheme: '#10B981',
    avatar: '🌍',
    description:
      'Provides real-time Arabic ↔ English translation for client communications, marketing content, and documents',
    capabilities: [
      'real_time_translation',
      'arabic_rtl_support',
      'document_translation',
      'tone_preservation',
      'property_terminology',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'agent'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 567,
      activeUsers: 7,
      systemHealth: 'optimal',
    },
    quickStats: { value: 567, label: 'Translations', change: 8.3 },
    dashboardUrl: '/owner/dashboard?tab=mira',
    apiEndpoints: ['/api/translate', '/api/translate/document', '/api/translate/detect'],
  },
  rex: {
    id: 'rex',
    name: 'Rex',
    title: 'Regulatory Document Verifier',
    department: 'compliance',
    icon: 'FileCheck',
    colorScheme: '#DC2626',
    avatar: '📋',
    description:
      'Verifies title deeds, NOCs, Emirates IDs, and government documents using DLD API and layout integrity checks',
    capabilities: [
      'document_verification',
      'title_deed_check',
      'noc_validation',
      'id_verification',
      'dld_api_integration',
      'fraud_detection',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'legal_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 134,
      activeUsers: 2,
      systemHealth: 'optimal',
    },
    quickStats: { value: 134, label: 'Docs Verified', change: 0 },
    dashboardUrl: '/owner/dashboard?tab=rex',
    apiEndpoints: [
      '/api/compliance/documents/verify',
      '/api/compliance/dld-check',
      '/api/compliance/id-verify',
    ],
  },
  iris: {
    id: 'iris',
    name: 'Iris',
    title: 'Virtual Staging & 3D Visualization AI',
    department: 'technology',
    icon: 'Eye',
    colorScheme: '#A855F7',
    avatar: '🎨',
    description:
      'Generates AI-powered virtual staging images, interactive 3D floor plans, and AR property tours',
    capabilities: [
      'virtual_staging',
      '3d_rendering',
      'ar_tour_generation',
      'floor_plan_conversion',
      'style_recommendations',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'marketing_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 89,
      activeUsers: 3,
      systemHealth: 'optimal',
    },
    quickStats: { value: 89, label: 'Stagings Generated', change: 12.1 },
    dashboardUrl: '/owner/dashboard?tab=iris',
    apiEndpoints: ['/api/staging/generate', '/api/staging/3d', '/api/staging/ar'],
  },
  apex: {
    id: 'apex',
    name: 'Apex',
    title: 'Agent Performance Coach',
    department: 'marketing',
    icon: 'TrendingUp',
    colorScheme: '#F59E0B',
    avatar: '🏆',
    description:
      'Monitors and coaches sales agents on performance metrics, client communication quality, and personal branding',
    capabilities: [
      'performance_tracking',
      'coaching_recommendations',
      'communication_analysis',
      'personal_branding',
      'target_setting',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'sales_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 312,
      activeUsers: 5,
      systemHealth: 'optimal',
    },
    quickStats: { value: 24, label: 'Agents Coached', change: 0 },
    dashboardUrl: '/owner/dashboard?tab=apex',
    apiEndpoints: [
      '/api/marketing/agent-performance',
      '/api/marketing/coaching',
      '/api/agents/metrics',
    ],
  },
  halo: {
    id: 'halo',
    name: 'Halo',
    title: 'Client Satisfaction & NPS Tracker',
    department: 'customer_experience',
    icon: 'Star',
    colorScheme: '#F472B6',
    avatar: '⭐',
    description:
      'Measures Net Promoter Score and CSAT after every sale, lease, and key client interaction',
    capabilities: [
      'nps_surveys',
      'csat_measurement',
      'feedback_collection',
      'trend_analysis',
      'alert_thresholds',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'sales_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 203,
      activeUsers: 4,
      systemHealth: 'optimal',
    },
    quickStats: { value: 72, label: 'NPS Score', change: 3.2 },
    dashboardUrl: '/owner/dashboard?tab=halo',
    apiEndpoints: ['/api/cx/nps/survey', '/api/cx/nps/scores', '/api/cx/feedback'],
  },
  oracle: {
    id: 'oracle',
    name: 'Oracle',
    title: 'Market Analyst Bot',
    department: 'data_and_ai',
    icon: 'BarChart2',
    colorScheme: '#0D9488',
    avatar: '🔮',
    description:
      'Synthesises real-time DLD transaction data, portal price feeds, and economic indicators into narrative market summaries',
    capabilities: [
      'market_synthesis',
      'dld_data_analysis',
      'price_trend_reporting',
      'opportunity_alerts',
      'report_generation',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'investment_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 78,
      activeUsers: 3,
      systemHealth: 'optimal',
    },
    quickStats: { value: 78, label: 'Reports Generated', change: 6.2 },
    dashboardUrl: '/owner/dashboard?tab=oracle',
    apiEndpoints: [
      '/api/intelligence/market-report',
      '/api/intelligence/summary',
      '/api/intelligence/alerts',
    ],
  },
  flux: {
    id: 'flux',
    name: 'Flux',
    title: 'Real-Time Market Data Feed',
    department: 'data_and_ai',
    icon: 'Activity',
    colorScheme: '#3B82F6',
    avatar: '⚡',
    description:
      'Continuously ingests DLD transaction records, portal price changes, UAE news, and developer announcements',
    capabilities: [
      'dld_feed_ingestion',
      'portal_price_monitoring',
      'news_scraping',
      'developer_updates',
      'data_normalisation',
    ],
    permissions: {
      viewableBy: ['owner', 'admin'],
      accessibleBy: ['owner'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 14203,
      activeUsers: 1,
      systemHealth: 'optimal',
    },
    quickStats: { value: 14203, label: 'Records Ingested', change: 0.8 },
    dashboardUrl: '/owner/dashboard?tab=flux',
    apiEndpoints: [
      '/api/intelligence/news-feed',
      '/api/intelligence/transactions',
      '/api/intelligence/prices',
    ],
  },
  nova: {
    id: 'nova',
    name: 'Nova',
    title: 'New Development & Off-Plan Tracker',
    department: 'data_and_ai',
    icon: 'Building',
    colorScheme: '#8B5CF6',
    avatar: '🏗️',
    description:
      'Monitors developer project milestones, payment plan releases, and launch events to keep the sales team ahead of new inventory',
    capabilities: [
      'milestone_tracking',
      'launch_alerts',
      'payment_plan_monitoring',
      'developer_news',
      'handover_schedule',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'sales_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'departmental',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 56,
      activeUsers: 3,
      systemHealth: 'optimal',
    },
    quickStats: { value: 19, label: 'Live Projects', change: 2.0 },
    dashboardUrl: '/owner/dashboard?tab=nova',
    apiEndpoints: [
      '/api/intelligence/off-plan',
      '/api/intelligence/developers',
      '/api/intelligence/launches',
    ],
  },
  quill: {
    id: 'quill',
    name: 'Quill',
    title: 'Document Generation Engine',
    department: 'data_and_ai',
    icon: 'FileText',
    colorScheme: '#6366F1',
    avatar: '✍️',
    description:
      'Generates SPAs, lease agreements, NOCs, invoices, market reports, and board summaries from templates and live CRM data',
    capabilities: [
      'spa_generation',
      'lease_drafting',
      'invoice_generation',
      'report_pdf',
      'template_management',
      'bulk_generation',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'legal_manager', 'finance_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 412,
      activeUsers: 4,
      systemHealth: 'optimal',
    },
    quickStats: { value: 412, label: 'Docs Generated', change: 9.3 },
    dashboardUrl: '/owner/dashboard?tab=quill',
    apiEndpoints: ['/api/documents/generate', '/api/documents/templates', '/api/documents/preview'],
  },
  lumen: {
    id: 'lumen',
    name: 'Lumen',
    title: 'Visual Analytics & Reporting Engine',
    department: 'data_and_ai',
    icon: 'BarChart',
    colorScheme: '#EC4899',
    avatar: '📊',
    description:
      'Renders charts, heat maps, geospatial visualisations, and exportable dashboards from CRM and market data',
    capabilities: [
      'chart_rendering',
      'heatmap_generation',
      'geospatial_mapping',
      'dashboard_builder',
      'pdf_export',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'sales_manager', 'marketing_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 287,
      activeUsers: 5,
      systemHealth: 'optimal',
    },
    quickStats: { value: 287, label: 'Reports Rendered', change: 4.7 },
    dashboardUrl: '/owner/dashboard?tab=lumen',
    apiEndpoints: ['/api/reports/charts/:type', '/api/reports/dashboards', '/api/reports/export'],
  },
  crest: {
    id: 'crest',
    name: 'Crest',
    title: 'Property Valuation Engine (AVM)',
    department: 'data_and_ai',
    icon: 'TrendingUp',
    colorScheme: '#10B981',
    avatar: '🏠',
    description:
      'Provides automated property valuations based on comparable DLD transactions, area trends, and market demand signals with a confidence score',
    capabilities: [
      'automated_valuation',
      'comparable_analysis',
      'confidence_scoring',
      'bulk_valuation',
      'valuation_history',
    ],
    permissions: {
      viewableBy: ['owner', 'admin', 'sales_manager', 'investment_manager'],
      accessibleBy: ['owner', 'admin'],
      dataAccessLevel: 'full',
    },
    metrics: {
      lastActive: null,
      tasksCompleted: 678,
      activeUsers: 4,
      systemHealth: 'optimal',
    },
    quickStats: { value: 96, label: 'Valuation Accuracy %', change: 0.4 },
    dashboardUrl: '/owner/dashboard?tab=crest',
    apiEndpoints: ['/api/valuation/property', '/api/valuation/bulk', '/api/valuation/history'],
  },
};

// ============================================================================
// DEPARTMENT COLORS
// ============================================================================

export const DEPARTMENT_COLORS: Record<string, string> = {
  operations: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  finance: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
  marketing: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
  executive: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
  compliance: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
  communications: 'linear-gradient(135deg, #25D366 0%, #128C7E 100%)',
  sales: 'linear-gradient(135deg, #8B5CF6 0%, #D946EF 100%)',
  technology: 'linear-gradient(135deg, #0EA5E9 0%, #06B6D4 100%)',
  legal: 'linear-gradient(135deg, #D4AF37 0%, #B8960C 100%)',
  intelligence: 'linear-gradient(135deg, #0D9488 0%, #0F766E 100%)',
  customer_experience: 'linear-gradient(135deg, #8B5CF6 0%, #7C3AED 100%)',
  data_and_ai: 'linear-gradient(135deg, #F97316 0%, #EA580C 100%)',
};

// ============================================================================
// SEED DATA GENERATORS
// ============================================================================

export const generateActivities = (): Activity[] => {
  const now = Date.now();
  return [
    {
      id: 1,
      assistantId: 'nadia',
      action: 'New lead captured from WhatsApp',
      target: 'Ahmed Al-Rashid',
      timestamp: new Date(now - 300000).toISOString(),
      type: 'success',
    },
    {
      id: 2,
      assistantId: 'clara',
      action: 'Lead stage updated to Qualified',
      target: 'Sarah Johnson',
      timestamp: new Date(now - 600000).toISOString(),
      type: 'success',
    },
    {
      id: 3,
      assistantId: 'mary',
      action: 'Property data imported',
      target: '23 new units from Excel',
      timestamp: new Date(now - 900000).toISOString(),
      type: 'success',
    },
    {
      id: 4,
      assistantId: 'theodora',
      action: 'Invoice generated',
      target: 'INV-2024-0156',
      timestamp: new Date(now - 1200000).toISOString(),
      type: 'info',
    },
    {
      id: 5,
      assistantId: 'sophia',
      action: 'Deal closed successfully',
      target: 'Villa 348 - AED 2.5M',
      timestamp: new Date(now - 1500000).toISOString(),
      type: 'success',
    },
    {
      id: 6,
      assistantId: 'nancy',
      action: 'Interview scheduled',
      target: 'Mohammed Ali - Sales Agent',
      timestamp: new Date(now - 1800000).toISOString(),
      type: 'pending',
    },
    {
      id: 7,
      assistantId: 'laila',
      action: 'KYC verification completed',
      target: 'James Wilson',
      timestamp: new Date(now - 2100000).toISOString(),
      type: 'success',
    },
    {
      id: 8,
      assistantId: 'nina',
      action: 'Bot session started',
      target: 'Lion0 WhatsApp Bot',
      timestamp: new Date(now - 2400000).toISOString(),
      type: 'active',
    },
    {
      id: 9,
      assistantId: 'daisy',
      action: 'Lease renewal processed',
      target: 'Unit 156 - Palm Views',
      timestamp: new Date(now - 2700000).toISOString(),
      type: 'success',
    },
    {
      id: 10,
      assistantId: 'olivia',
      action: 'Campaign launched',
      target: 'Summer Property Showcase',
      timestamp: new Date(now - 3000000).toISOString(),
      type: 'success',
    },
    {
      id: 11,
      assistantId: 'aurora',
      action: 'System health check completed',
      target: 'All services healthy',
      timestamp: new Date(now - 3300000).toISOString(),
      type: 'success',
    },
    {
      id: 12,
      assistantId: 'aurora',
      action: 'Deployment successful',
      target: 'WhatsApp CRM v2.4.1',
      timestamp: new Date(now - 3600000).toISOString(),
      type: 'success',
    },
    {
      id: 13,
      assistantId: 'linda',
      action: 'OpenClaw gateway session initialised',
      target: 'Agent channel: agent_7',
      timestamp: new Date(now - 3900000).toISOString(),
      type: 'active',
    },
    {
      id: 14,
      assistantId: 'archer',
      action: 'Lead scored',
      target: 'Lead #1047 — Score 87/100',
      timestamp: new Date(now - 4200000).toISOString(),
      type: 'success',
    },
    {
      id: 15,
      assistantId: 'prism',
      action: 'Property match generated',
      target: 'Client Rania Hassan — 5 matches found',
      timestamp: new Date(now - 4500000).toISOString(),
      type: 'success',
    },
    {
      id: 16,
      assistantId: 'cipher',
      action: 'Market report generated',
      target: 'DAMAC Hills 2 — Q2 Forecast',
      timestamp: new Date(now - 4800000).toISOString(),
      type: 'info',
    },
    {
      id: 17,
      assistantId: 'flux',
      action: 'DLD feed ingested',
      target: '342 new transactions',
      timestamp: new Date(now - 5100000).toISOString(),
      type: 'success',
    },
    {
      id: 18,
      assistantId: 'oracle',
      action: 'Market summary published',
      target: 'Dubai Weekly Intelligence Report',
      timestamp: new Date(now - 5400000).toISOString(),
      type: 'success',
    },
    {
      id: 19,
      assistantId: 'quill',
      action: 'SPA document generated',
      target: 'Buyer: Omar Khalid — Unit 4B',
      timestamp: new Date(now - 5700000).toISOString(),
      type: 'success',
    },
    {
      id: 20,
      assistantId: 'crest',
      action: 'Property valuation completed',
      target: 'Unit 789 — AED 1.85M (confidence 94%)',
      timestamp: new Date(now - 6000000).toISOString(),
      type: 'success',
    },
    {
      id: 21,
      assistantId: 'rex',
      action: 'Title deed verified',
      target: 'Plot 22, Al Barsha South',
      timestamp: new Date(now - 6300000).toISOString(),
      type: 'success',
    },
    {
      id: 22,
      assistantId: 'halo',
      action: 'NPS survey dispatched',
      target: '12 clients post-handover',
      timestamp: new Date(now - 6600000).toISOString(),
      type: 'info',
    },
    {
      id: 23,
      assistantId: 'kairos',
      action: 'VIP viewing arranged',
      target: 'Client: Sheikh Mansoor — Penthouse tour',
      timestamp: new Date(now - 6900000).toISOString(),
      type: 'success',
    },
    {
      id: 24,
      assistantId: 'hunter',
      action: 'Prospect list enriched',
      target: '18 new high-value investor leads',
      timestamp: new Date(now - 7200000).toISOString(),
      type: 'success',
    },
    {
      id: 25,
      assistantId: 'sentinel',
      action: 'Maintenance alert triggered',
      target: 'Unit 302 — HVAC fault detected',
      timestamp: new Date(now - 7500000).toISOString(),
      type: 'warning',
    },
    {
      id: 26,
      assistantId: 'vesta',
      action: 'Construction milestone updated',
      target: 'Akoya Oxygen Phase 3 — 78% complete',
      timestamp: new Date(now - 7800000).toISOString(),
      type: 'info',
    },
    {
      id: 27,
      assistantId: 'henry',
      action: 'Audit log archived',
      target: '1,200 events from last 24 hours',
      timestamp: new Date(now - 8100000).toISOString(),
      type: 'success',
    },
    {
      id: 28,
      assistantId: 'maven',
      action: 'Portfolio analysis completed',
      target: 'Investor Client: Khalid Investments LLC',
      timestamp: new Date(now - 8400000).toISOString(),
      type: 'success',
    },
    {
      id: 29,
      assistantId: 'sage',
      action: 'Mortgage calculation run',
      target: 'Client Fatima Noor — ENBD comparison',
      timestamp: new Date(now - 8700000).toISOString(),
      type: 'info',
    },
    {
      id: 30,
      assistantId: 'mira',
      action: 'Document translated',
      target: 'SPA contract — Arabic → English',
      timestamp: new Date(now - 9000000).toISOString(),
      type: 'success',
    },
  ];
};

export const generateNotifications = (): Record<string, Notification[]> => {
  const now = Date.now();
  return {
    nadia: [
      {
        id: 'n1',
        type: 'lead',
        message: 'New lead from WhatsApp',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 120000).toISOString(),
      },
      {
        id: 'n2',
        type: 'task',
        message: 'Agent quota exceeded',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 300000).toISOString(),
      },
    ],
    nina: [
      {
        id: 'n3',
        type: 'bot',
        message: 'Bot session expired',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 360000).toISOString(),
      },
      {
        id: 'n4',
        type: 'flow',
        message: 'New NLP intent detected — update flow',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 720000).toISOString(),
      },
    ],
    linda: [
      {
        id: 'n5',
        type: 'session',
        message: 'OpenClaw gateway reconnected on agent_07',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 480000).toISOString(),
      },
      {
        id: 'n6',
        type: 'session',
        message: 'QR code scan required for agent_03',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 900000).toISOString(),
      },
    ],
    mary: [
      {
        id: 'n7',
        type: 'inventory',
        message: 'Excel import completed — 23 new units added',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 540000).toISOString(),
      },
    ],
    nancy: [
      {
        id: 'n8',
        type: 'hr',
        message: 'Performance review due for 3 agents',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 600000).toISOString(),
      },
    ],
    daisy: [
      {
        id: 'n9',
        type: 'lease',
        message: '5 leases expiring within 30 days',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 660000).toISOString(),
      },
    ],
    sentinel: [
      {
        id: 'n10',
        type: 'maintenance',
        message: 'HVAC fault detected — Unit 302',
        severity: 'critical',
        isRead: false,
        timestamp: new Date(now - 420000).toISOString(),
      },
    ],
    vesta: [
      {
        id: 'n11',
        type: 'construction',
        message: 'Snagging report submitted for Phase 3',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 780000).toISOString(),
      },
    ],
    juno: [
      {
        id: 'n12',
        type: 'facilities',
        message: 'Energy usage 12% above baseline — Building 7',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 840000).toISOString(),
      },
    ],
    clara: [
      {
        id: 'n13',
        type: 'lead',
        message: 'Lead requires follow-up',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 180000).toISOString(),
      },
      {
        id: 'n14',
        type: 'lead',
        message: '3 leads stagnant for 7+ days',
        severity: 'critical',
        isRead: false,
        timestamp: new Date(now - 960000).toISOString(),
      },
    ],
    sophia: [
      {
        id: 'n15',
        type: 'deal',
        message: 'Deal awaiting approval',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 420000).toISOString(),
      },
      {
        id: 'n16',
        type: 'pipeline',
        message: 'Monthly target at 72% — 8 days remaining',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 1080000).toISOString(),
      },
    ],
    hunter: [
      {
        id: 'n17',
        type: 'prospects',
        message: '18 new high-value prospects identified',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 1140000).toISOString(),
      },
    ],
    archer: [
      {
        id: 'n18',
        type: 'scoring',
        message: '5 leads scored above 90 — review now',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 1200000).toISOString(),
      },
    ],
    prism: [
      {
        id: 'n19',
        type: 'matching',
        message: 'New high-match properties available for 4 clients',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 1260000).toISOString(),
      },
    ],
    kairos: [
      {
        id: 'n20',
        type: 'vip',
        message: 'VIP client Sheikh Mansoor enquiry received',
        severity: 'critical',
        isRead: false,
        timestamp: new Date(now - 1320000).toISOString(),
      },
    ],
    theodora: [
      {
        id: 'n21',
        type: 'payment',
        message: 'Invoice overdue',
        severity: 'critical',
        isRead: false,
        timestamp: new Date(now - 240000).toISOString(),
      },
      {
        id: 'n22',
        type: 'finance',
        message: 'Monthly reconciliation due in 2 days',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 1380000).toISOString(),
      },
    ],
    maven: [
      {
        id: 'n23',
        type: 'portfolio',
        message: 'Portfolio yield dropped 0.3% — review assets',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 1440000).toISOString(),
      },
    ],
    sage: [
      {
        id: 'n24',
        type: 'finance',
        message: 'EIBOR rate updated — recalculate 3 pending mortgages',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 1500000).toISOString(),
      },
    ],
    olivia: [
      {
        id: 'n25',
        type: 'campaign',
        message: 'Summer campaign click-through rate up 18%',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 1560000).toISOString(),
      },
    ],
    apex: [
      {
        id: 'n26',
        type: 'performance',
        message: '2 agents below KPI threshold this week',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 1620000).toISOString(),
      },
    ],
    zoe: [
      {
        id: 'n27',
        type: 'meeting',
        message: 'Meeting in 30 minutes',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 60000).toISOString(),
      },
      {
        id: 'n28',
        type: 'suggestion',
        message: '3 new executive suggestions pending review',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 1680000).toISOString(),
      },
    ],
    laila: [
      {
        id: 'n29',
        type: 'kyc',
        message: '4 KYC profiles pending review',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 1740000).toISOString(),
      },
    ],
    rex: [
      {
        id: 'n30',
        type: 'document',
        message: 'Title deed verification failed — Plot 44B',
        severity: 'critical',
        isRead: false,
        timestamp: new Date(now - 1800000).toISOString(),
      },
    ],
    evangeline: [
      {
        id: 'n31',
        type: 'legal',
        message: 'Contract clause flagged for review',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 1860000).toISOString(),
      },
    ],
    aurora: [
      {
        id: 'n32',
        type: 'system',
        message: 'API response time spike detected',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 1920000).toISOString(),
      },
    ],
    hazel: [
      {
        id: 'n33',
        type: 'ui',
        message: 'Accessibility audit complete — 2 issues found',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 1980000).toISOString(),
      },
    ],
    willow: [
      {
        id: 'n34',
        type: 'backend',
        message: 'Database query optimisation needed on /api/leads',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 2040000).toISOString(),
      },
    ],
    henry: [
      {
        id: 'n35',
        type: 'audit',
        message: 'SLA breach detected — lead response > 4 hours',
        severity: 'critical',
        isRead: false,
        timestamp: new Date(now - 2100000).toISOString(),
      },
    ],
    iris: [
      {
        id: 'n36',
        type: 'staging',
        message: 'Virtual staging complete — Unit 15C ready for listing',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 2160000).toISOString(),
      },
    ],
    cipher: [
      {
        id: 'n37',
        type: 'market',
        message: 'Price correction detected in Jumeirah Village Circle',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 2220000).toISOString(),
      },
    ],
    atlas: [
      {
        id: 'n38',
        type: 'intelligence',
        message: 'New off-plan project launch: Emaar Creek Views III',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 2280000).toISOString(),
      },
    ],
    echo: [
      {
        id: 'n39',
        type: 'communication',
        message: 'Client Ali Hassan — no contact in 14 days',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 2340000).toISOString(),
      },
    ],
    mira: [
      {
        id: 'n40',
        type: 'translation',
        message: 'Arabic SPA translation ready for review',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 2400000).toISOString(),
      },
    ],
    halo: [
      {
        id: 'n41',
        type: 'nps',
        message: 'NPS score dropped to 68 — below target of 70',
        severity: 'critical',
        isRead: false,
        timestamp: new Date(now - 2460000).toISOString(),
      },
    ],
    oracle: [
      {
        id: 'n42',
        type: 'market',
        message: 'Weekly market report published and ready',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 2520000).toISOString(),
      },
    ],
    flux: [
      {
        id: 'n43',
        type: 'data',
        message: 'DLD feed delay — last update 45 min ago',
        severity: 'warning',
        isRead: false,
        timestamp: new Date(now - 2580000).toISOString(),
      },
    ],
    nova: [
      {
        id: 'n44',
        type: 'offplan',
        message: 'New payment plan released: DAMAC Lagoons',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 2640000).toISOString(),
      },
    ],
    quill: [
      {
        id: 'n45',
        type: 'document',
        message: 'Bulk SPA generation queued — 8 documents',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 2700000).toISOString(),
      },
    ],
    lumen: [
      {
        id: 'n46',
        type: 'report',
        message: 'Q2 dashboard exported successfully',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 2760000).toISOString(),
      },
    ],
    crest: [
      {
        id: 'n47',
        type: 'valuation',
        message: 'Bulk valuation complete — 34 properties updated',
        severity: 'info',
        isRead: false,
        timestamp: new Date(now - 2820000).toISOString(),
      },
    ],
  };
};

export const generateTasks = (): Record<string, Task[]> => ({
  nadia: [
    {
      id: 't_nadia_1',
      title: 'Review unassigned conversations',
      priority: 'high',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
    {
      id: 't_nadia_2',
      title: 'Send broadcast to past investors re: Q3 projects',
      priority: 'medium',
      status: 'in_progress',
      assignedTo: 'agent_2',
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
  ],
  nina: [
    {
      id: 't_nina_1',
      title: 'Update FAQ flow with new payment plan options',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
    {
      id: 't_nina_2',
      title: 'Test Arabic intent recognition for new bot version',
      priority: 'high',
      status: 'in_progress',
      assignedTo: 'agent_1',
      dueDate: new Date().toISOString(),
    },
  ],
  linda: [
    {
      id: 't_linda_1',
      title: 'Re-link agent_03 WhatsApp session via QR code',
      priority: 'high',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
    {
      id: 't_linda_2',
      title: 'Configure OpenClaw gateway for 2 new agent channels',
      priority: 'medium',
      status: 'in_progress',
      assignedTo: 'agent_5',
      dueDate: new Date(Date.now() + 172800000).toISOString(),
    },
  ],
  mary: [
    {
      id: 't_mary_1',
      title: 'Import DAMAC Hills 2 Phase 4 unit list from Excel',
      priority: 'high',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
    {
      id: 't_mary_2',
      title: 'Update floor plans for units 400–450',
      priority: 'medium',
      status: 'in_progress',
      assignedTo: 'agent_3',
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
  ],
  nancy: [
    {
      id: 't_nancy_1',
      title: 'Complete Q2 performance reviews for all agents',
      priority: 'high',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 259200000).toISOString(),
    },
    {
      id: 't_nancy_2',
      title: 'Onboard 2 new sales agents — prepare access & documents',
      priority: 'medium',
      status: 'in_progress',
      assignedTo: 'agent_4',
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
  ],
  daisy: [
    {
      id: 't_daisy_1',
      title: 'Process 5 upcoming lease renewals',
      priority: 'high',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 172800000).toISOString(),
    },
    {
      id: 't_daisy_2',
      title: 'Follow up on maintenance ticket #MT-0442',
      priority: 'medium',
      status: 'in_progress',
      assignedTo: 'agent_6',
      dueDate: new Date().toISOString(),
    },
  ],
  sentinel: [
    {
      id: 't_sentinel_1',
      title: 'Resolve HVAC fault alert — Unit 302',
      priority: 'high',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
    {
      id: 't_sentinel_2',
      title: 'Schedule bi-annual property inspection — Buildings 1–5',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 604800000).toISOString(),
    },
  ],
  vesta: [
    {
      id: 't_vesta_1',
      title: 'Submit snagging report for Akoya Phase 3 handover',
      priority: 'high',
      status: 'in_progress',
      assignedTo: 'agent_2',
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
    {
      id: 't_vesta_2',
      title: 'Chase developer response on 7 open defect tickets',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 259200000).toISOString(),
    },
  ],
  juno: [
    {
      id: 't_juno_1',
      title: 'Investigate energy spike — Building 7',
      priority: 'high',
      status: 'in_progress',
      assignedTo: 'agent_3',
      dueDate: new Date().toISOString(),
    },
    {
      id: 't_juno_2',
      title: 'Organise community BBQ event — Lagoons Cluster',
      priority: 'low',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 604800000).toISOString(),
    },
  ],
  clara: [
    {
      id: 't_clara_1',
      title: 'Follow up with hot leads',
      priority: 'high',
      status: 'in_progress',
      assignedTo: 'agent_1',
      dueDate: new Date().toISOString(),
    },
    {
      id: 't_clara_2',
      title: 'Re-qualify 3 stagnant leads from last month',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
  ],
  sophia: [
    {
      id: 't_sophia_1',
      title: 'Assign 6 unassigned leads to available agents',
      priority: 'high',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
    {
      id: 't_sophia_2',
      title: 'Review pipeline for monthly target forecast',
      priority: 'medium',
      status: 'in_progress',
      assignedTo: 'agent_2',
      dueDate: new Date(Date.now() + 172800000).toISOString(),
    },
  ],
  hunter: [
    {
      id: 't_hunter_1',
      title: 'Enrich 18 new investor prospects with contact data',
      priority: 'high',
      status: 'in_progress',
      assignedTo: 'agent_4',
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
    {
      id: 't_hunter_2',
      title: 'Run competitor analysis on Emaar sales in JVC',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 259200000).toISOString(),
    },
  ],
  archer: [
    {
      id: 't_archer_1',
      title: 'Score all leads from last 48 hours',
      priority: 'high',
      status: 'in_progress',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
    {
      id: 't_archer_2',
      title: 'Review scoring model rules with sales manager',
      priority: 'medium',
      status: 'pending',
      assignedTo: 'agent_1',
      dueDate: new Date(Date.now() + 172800000).toISOString(),
    },
  ],
  prism: [
    {
      id: 't_prism_1',
      title: 'Run property match for 4 new buyer requirements',
      priority: 'high',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
    {
      id: 't_prism_2',
      title: 'Re-index inventory after new unit upload',
      priority: 'medium',
      status: 'in_progress',
      assignedTo: null,
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
  ],
  kairos: [
    {
      id: 't_kairos_1',
      title: 'Arrange penthouse viewing for Sheikh Mansoor',
      priority: 'high',
      status: 'in_progress',
      assignedTo: 'agent_5',
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
    {
      id: 't_kairos_2',
      title: 'Coordinate interior design partner for VIP client handover',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 259200000).toISOString(),
    },
  ],
  theodora: [
    {
      id: 't_theodora_1',
      title: 'Process pending invoices',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
    {
      id: 't_theodora_2',
      title: 'Prepare monthly P&L summary for managing director',
      priority: 'high',
      status: 'in_progress',
      assignedTo: 'agent_3',
      dueDate: new Date(Date.now() + 172800000).toISOString(),
    },
  ],
  maven: [
    {
      id: 't_maven_1',
      title: 'Update portfolio analysis for Khalid Investments',
      priority: 'high',
      status: 'in_progress',
      assignedTo: null,
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
    {
      id: 't_maven_2',
      title: 'Review yield projections after EIBOR rate change',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 259200000).toISOString(),
    },
  ],
  sage: [
    {
      id: 't_sage_1',
      title: 'Recalculate mortgages using updated EIBOR rate',
      priority: 'high',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
    {
      id: 't_sage_2',
      title: 'Prepare bank comparison report for client Fatima Noor',
      priority: 'medium',
      status: 'in_progress',
      assignedTo: 'agent_2',
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
  ],
  olivia: [
    {
      id: 't_olivia_1',
      title: 'Schedule social posts for Eid property campaign',
      priority: 'high',
      status: 'in_progress',
      assignedTo: 'agent_6',
      dueDate: new Date(Date.now() + 172800000).toISOString(),
    },
    {
      id: 't_olivia_2',
      title: 'Analyse last campaign ROI and submit report',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 259200000).toISOString(),
    },
  ],
  apex: [
    {
      id: 't_apex_1',
      title: 'Review KPI scores for underperforming agents',
      priority: 'high',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
    {
      id: 't_apex_2',
      title: 'Generate individual coaching plans for 2 agents',
      priority: 'medium',
      status: 'in_progress',
      assignedTo: 'agent_1',
      dueDate: new Date(Date.now() + 259200000).toISOString(),
    },
  ],
  zoe: [
    {
      id: 't_zoe_1',
      title: 'Prepare weekly executive summary for managing director',
      priority: 'high',
      status: 'in_progress',
      assignedTo: null,
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
    {
      id: 't_zoe_2',
      title: 'Review 3 pending AI assistant suggestions',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
  ],
  laila: [
    {
      id: 't_laila_1',
      title: 'Complete KYC review for 4 pending client profiles',
      priority: 'high',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
    {
      id: 't_laila_2',
      title: 'Run monthly AML screening batch',
      priority: 'high',
      status: 'in_progress',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
  ],
  rex: [
    {
      id: 't_rex_1',
      title: 'Investigate failed title deed verification — Plot 44B',
      priority: 'high',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
    {
      id: 't_rex_2',
      title: 'Verify 6 NOCs submitted this week',
      priority: 'medium',
      status: 'in_progress',
      assignedTo: 'agent_4',
      dueDate: new Date(Date.now() + 172800000).toISOString(),
    },
  ],
  evangeline: [
    {
      id: 't_evangeline_1',
      title: 'Review flagged contract clause — Client AL Holdings',
      priority: 'high',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
    {
      id: 't_evangeline_2',
      title: 'Update regulatory compliance checklist for Q3',
      priority: 'medium',
      status: 'in_progress',
      assignedTo: 'agent_3',
      dueDate: new Date(Date.now() + 259200000).toISOString(),
    },
  ],
  aurora: [
    {
      id: 't_aurora_1',
      title: 'Investigate API response time spike on /api/leads',
      priority: 'high',
      status: 'in_progress',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
    {
      id: 't_aurora_2',
      title: 'Plan next deployment: CRM v2.5 release',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 604800000).toISOString(),
    },
  ],
  hazel: [
    {
      id: 't_hazel_1',
      title: 'Fix 2 accessibility issues from latest audit',
      priority: 'high',
      status: 'in_progress',
      assignedTo: null,
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
    {
      id: 't_hazel_2',
      title: 'Build new property card component for mobile view',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 259200000).toISOString(),
    },
  ],
  willow: [
    {
      id: 't_willow_1',
      title: 'Optimise /api/leads query — reduce response time',
      priority: 'high',
      status: 'in_progress',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
    {
      id: 't_willow_2',
      title: 'Add Redis caching layer for property listing endpoints',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 259200000).toISOString(),
    },
  ],
  henry: [
    {
      id: 't_henry_1',
      title: 'Investigate SLA breach — lead response > 4 hours',
      priority: 'high',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
    {
      id: 't_henry_2',
      title: 'Archive last quarter audit logs to cold storage',
      priority: 'low',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 604800000).toISOString(),
    },
  ],
  iris: [
    {
      id: 't_iris_1',
      title: 'Generate virtual staging for 5 new listings',
      priority: 'high',
      status: 'in_progress',
      assignedTo: 'agent_6',
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
    {
      id: 't_iris_2',
      title: 'Create AR tour for penthouse unit 38B',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 172800000).toISOString(),
    },
  ],
  cipher: [
    {
      id: 't_cipher_1',
      title: 'Generate Q3 price prediction report for JVC',
      priority: 'high',
      status: 'in_progress',
      assignedTo: null,
      dueDate: new Date(Date.now() + 172800000).toISOString(),
    },
    {
      id: 't_cipher_2',
      title: 'Review economic indicator data feed — last ingestion stale',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
  ],
  atlas: [
    {
      id: 't_atlas_1',
      title: 'Analyse feasibility of Emaar Creek Views III investment',
      priority: 'high',
      status: 'in_progress',
      assignedTo: null,
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
    {
      id: 't_atlas_2',
      title: 'Update developer track record scores for Q2',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 259200000).toISOString(),
    },
  ],
  echo: [
    {
      id: 't_echo_1',
      title: 'Flag all clients with no contact in 14+ days',
      priority: 'high',
      status: 'in_progress',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
    {
      id: 't_echo_2',
      title: 'Index 500 WhatsApp messages from last sync',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
  ],
  mira: [
    {
      id: 't_mira_1',
      title: 'Translate 3 pending Arabic property descriptions',
      priority: 'high',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
    {
      id: 't_mira_2',
      title: 'Translate SPA contract for client Hassan Al-Farsi',
      priority: 'medium',
      status: 'in_progress',
      assignedTo: 'agent_2',
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
  ],
  halo: [
    {
      id: 't_halo_1',
      title: 'Investigate drop in NPS — dispatch follow-up survey',
      priority: 'high',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
    {
      id: 't_halo_2',
      title: 'Send post-handover CSAT survey to 12 clients',
      priority: 'medium',
      status: 'in_progress',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
  ],
  oracle: [
    {
      id: 't_oracle_1',
      title: 'Publish Dubai weekly intelligence report',
      priority: 'high',
      status: 'in_progress',
      assignedTo: null,
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
    {
      id: 't_oracle_2',
      title: 'Set up opportunity alert for Dubai Islands launches',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 259200000).toISOString(),
    },
  ],
  flux: [
    {
      id: 't_flux_1',
      title: 'Resolve DLD feed delay — reconnect data source',
      priority: 'high',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
    {
      id: 't_flux_2',
      title: 'Add PropertyFinder price feed integration',
      priority: 'medium',
      status: 'in_progress',
      assignedTo: null,
      dueDate: new Date(Date.now() + 259200000).toISOString(),
    },
  ],
  nova: [
    {
      id: 't_nova_1',
      title: 'Log new DAMAC Lagoons payment plan details',
      priority: 'high',
      status: 'in_progress',
      assignedTo: null,
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
    {
      id: 't_nova_2',
      title: 'Set launch alert for upcoming Meraas project',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 172800000).toISOString(),
    },
  ],
  quill: [
    {
      id: 't_quill_1',
      title: 'Generate 8 SPAs for pending transactions',
      priority: 'high',
      status: 'in_progress',
      assignedTo: null,
      dueDate: new Date().toISOString(),
    },
    {
      id: 't_quill_2',
      title: 'Update SPA template with new RERA clause',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 172800000).toISOString(),
    },
  ],
  lumen: [
    {
      id: 't_lumen_1',
      title: 'Build Q2 sales performance dashboard for MD review',
      priority: 'high',
      status: 'in_progress',
      assignedTo: null,
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
    {
      id: 't_lumen_2',
      title: 'Generate geographic heat map for lead sources',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 259200000).toISOString(),
    },
  ],
  crest: [
    {
      id: 't_crest_1',
      title: 'Run bulk valuation on 34 newly listed properties',
      priority: 'high',
      status: 'in_progress',
      assignedTo: null,
      dueDate: new Date(Date.now() + 86400000).toISOString(),
    },
    {
      id: 't_crest_2',
      title: 'Recalibrate valuation model with latest DLD data',
      priority: 'medium',
      status: 'pending',
      assignedTo: null,
      dueDate: new Date(Date.now() + 259200000).toISOString(),
    },
  ],
});
